### ISSUE TITLE
"Assemblies" in Domain umbenennen?

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#100]
Bitte erst abklären, noch nicht umsetzen.

Welche Auswirkungen hätte ein umbenennen des Wortes assemblies in der Domain. Bsp:

https://dialogluzern.ch/assemblies/qvr
--> https://dialogluzern.ch/organisationen/qvr

**Comment by carlobeltrame** [comment]
Eine vollständige Abklärung aller Auswirkungen vorab ist schwierig. In der Theorie müsste so eine Umbenennung möglich sein. Man riskiert aber, besonders wenn die Applikation bereits läuft, bestehende Links sonstwo auf dem Internet kaputt zu machen (und je nach dem auch intern, ähnlich wie es beim Domain-Wechsel mit den eingebetteten Bildern geschehen ist #78). Zusätzlich zur Umbenennung würde ich also die "alte" URL noch weiter gültig behalten. Ich sehe ein paar verschiedene Möglichkeiten:

* **Umbenennen auf /organisationen, /assemblies abschaffen**
 riskant für interne sowie externe Links aus oben genannten Gründen.
* **Umbenennen auf /organisationen, /assemblies weiterleiten auf /organisationen**
  eher safe, die meisten externen und internen Verlinkungen sollten damit klarkommen
* **/organisationen weiterleiten auf /assemblies**
  sehr safe, sollte keine Probleme verursachen, aber die URL die schlussendlich im Browser angezeigt wird ist wieder /assemblies.

Was ist denn der Hintergrund dieser Anfrage? Möchtet ihr einfach schönere Links für auf Flyern etc. haben? Wäre das dann ein Thema für #101?

Oder gehts wirklich um die URL in der Adresszeile des Browsers? Der Pfad (also alles hinter dialogluzern.ch/) wird ja inzwischen von vielen Browsern sehr unscheinbar hellgrau angezeigt (wenn überhaupt), ich bezweifle dass viele User die URL je vollständig lesen und durchschauen (und durchschauen müssen).

Wäre dialogluzern.ch mehrsprachig, würde dazu noch ein weiteres "Problem" kommen: Nämlich dass /organisationen für andere Sprachen sogleich wieder inkorrekt wäre.
