### ISSUE TITLE
Einfachere URLs für Organisation und Projekte

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#101]
Welche Möglichkeiten seht ihr, damit wir Organisationen oder auch Partizipationsprozessen/Projekten die Möglichkeit bieten könnten, einfachere URLs zu kommunizieren?

Bsp. für Partizipationsprozesse:
https://projekt.dialogluzern.ch 
führt zu 
https://dialogluzern.ch/processes/dasprojekt

oder für Organisationen:
qv-sbo.dialogluzern.ch
führt zu 
https://dialogluzern.ch/assemblies/qv-sbo

Müssten wir dies allenfalls als zusätzliche DNS-Einträge bei Metanet anpassen und falls ja, wie genau?

**Comment by carlobeltrame** [comment]
Das haben wir in Issue #21 schon beschrieben. Nochmals zusammengefasst, für Subdomains (projekt.dialogluzern.ch) muss man sicher als erstes mal einen DNS-Eintrag einrichten sodass er auf die gleiche IP zeigt wie dialogluzern.ch (Aufwand bei euch für jede Organisation), und dann noch eine der von Thomas beschriebenen Optionen umsetzen (Aufwand bei uns für ein wenig Entwicklung und Deployment).

Wenn statt Subdomains auch Pfade (dialogluzern.ch/projekt) in Frage kämen, gäbe es ein [Modul](https://github.com/OpenSourcePolitics/decidim-urlaliases) dafür, mit dem ihr das ohne Eingriff von Puzzle einrichten könntet.

**Comment by innosmith** [comment]
@carlobeltrame: Besten Dank, diese Abklärungen habe ich nicht gesehen. Dann bitte mit dem Modul umsetzen, sodass wir die meisten Wünsche damit lösen können.

**Comment by innosmith** [comment]
@Naadjjaa zur Info

**Comment by innosmith** [comment]
Bitte das Modul https://github.com/OpenSourcePolitics/decidim-urlaliases auf INT und dann PROD installieren, damit wir selber einfachere URLs definieren können.
