### ISSUE TITLE
Klick auf Pin führt bei einigen Veranstaltungen ins Leere

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#103]
Auf der Veranstaltungs-Seite kann man in der Karte die Veranstaltungen via Klick auf den Pin anschauen. Bei einigen Pins funktioniert das nicht korrekt. Man landet "im Grünen" und die Infos werden nicht angezeigt.

**Comment by Naadjjaa** [comment]
https://user-images.githubusercontent.com/75797851/114167452-3bc1c780-992f-11eb-97a0-b60adece62f9.mp4

**Comment by carlobeltrame** [comment]
Ich glaube das tritt auf, wenn das geöffnete "Fensterli" so hoch ist, dass der Pin ausser Sicht gescrollt werden muss um das Fensterli komplett anzuzeigen. Die grosse Höhe wiederum ist verursacht durch das eingebettete Bild bei dieser Veranstaltung.

Ich kann entweder untersuchen ob man das automatische Ausblenden der Fensterli ausschalten kann, oder ob wir z.B. Bilder da drin nicht anzeigen können. Was wäre euch lieber?

**Comment by Naadjjaa** [comment]
Wie ich das verstehe, werden die Bilder eh nur aus dem Textteil gezogen. Ein offizielles Veranstaltungsbild ist nicht vorgesehen. Daher gerne die Bilder im Fensterli nicht anzeigen.

**Comment by carlobeltrame** [comment]
Der Text an sich kann wies aussieht auch ohne Bilder die Grösse des Fensterli immer noch sprengen, je nach dem wie ausführlich die Beschreibung ist. Ich habe nun stattdessen wenn nötig einen Scrollbalken eingefügt, und die Höhe des Fensterli auf eine sinnvolle Maximalhöhe limitiert. Ist auf Integration testbar.

Bei den Anlässen von Franco Luzern geht aber noch etwas anderes schief, das muss ich noch näher untersuchen.

**Comment by Naadjjaa** [comment]
@carlobeltrame @bsantschi Mir war nicht bewusst, dass ich hier noch zustimmen muss. Wäre es möglich das heute noch auf PROD zu übertragen? Wir bewerben aktuell einen Event und die Seite sieht aktuell echt nicht schön aus: https://dialogluzern.ch/meetings

**Comment by bsantschi** [comment]
Liebe @Naadjjaa, bitte entschuldige, aber Thomas und Carlo arbeiten heute nicht. Wir gehen das gerne nächste Woche an.

**Comment by carlobeltrame** [comment]
@Naadjjaa Der Fix den ich gemacht hatte war schon lange auf Prod deployed, die Scrollbalken in den Popup-Fensterli waren das Resultat. Aber was eure Meeting-Ansicht kaputt gemacht hat hatte nichts mit den Fensterli zu tun.

Zwei Events [[1]](https://dialogluzern.ch/assemblies/luzernnord/f/22/meetings/46) [[2]](https://dialogluzern.ch/assemblies/francoluzern/f/12/meetings/61) hatten eine Adresse ausserhalb von Luzern gesetzt (Zug und Stansstad). Die Karte versucht standardmässig, soweit rauszuzoomen dass alle Pins angezeigt werden, aber die luzerner GIS-Karten haben halt kein so weites Zoom-Level.

Ich weiss nicht genau, wie diese Pins überhaupt zustande gekommen sind, denn eigentlich filtern wir bei der Umrechnung von Adresse in Koordinaten nach Orten die sich in Luzern befinden... Aber man kann die Pins neuerdings sowieso herumziehen, daher bringts wohl nichts sich darauf zu verlassen.

Als Fix filtere ich jetzt neu alle Pins raus, die sich ausserhalb eines rechteckigen Bereichs um Luzern befinden. Das bedeutet gleichzeitig auch, dass bei solchen Events auf der Detailansicht die Übersicht von Luzern ohne Pins angezeigt wird.

Das am 13. April erwähnte weitere Problem mit den Events von Franco Luzern kann ich aktuell nicht mehr reproduzieren. Ich würde vorschlagen, dass wir ein weiteres Issue dazu aufmachen, wenn nochmals etwas auftritt. Vielleicht wurde es ja auch mit decidim 0.24 gefixt, wer weiss.

**Comment by Naadjjaa** [comment]
@carlobeltrame Falls unserer Nachbargemeinden auch auf die Plattform kommen sollten, müssen wir das Rechteck wohl etwas erweitern? Ich schliesse das Ticket für den Moment.

**Comment by carlobeltrame** [comment]
> @carlobeltrame Falls unserer Nachbargemeinden auch auf die Plattform kommen sollten, müssen wir das Rechteck wohl etwas erweitern? Ich schliesse das Ticket für den Moment.

Ja, genau. Und zudem wären dann die stadtluzerner GIS-Karten nicht mehr ausreichend oder? Die decken ja keine Nachbargemeinden ab.
