### ISSUE TITLE
Symbol auf Karte bei Handynutzung

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#104]
Bei Kartennutzung auf dem Handy ist der Wechsel der Kartenansichten ein weisses Viereck. Auf dem Desktop gibt es hier ein Symbol. Ist das einfach zu beheben?

**Comment by Naadjjaa** [comment]
![1617964239817](https://user-images.githubusercontent.com/75797851/114167994-f5209d00-992f-11eb-94f3-14fd78fd1525.jpg)

**Comment by Naadjjaa** [comment]
@Kagemaru Bei mir funktioniert dies nicht. Ich sehe immernoch das weisse Viereck.

**Comment by Kagemaru** [comment]
Testen mit Browserstack
