### ISSUE TITLE
Navigation Maps weg?

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#105]
Gibt es einen Grund, weshalb Navigation Maps nicht mehr auf der Testplattform ist? Wir würden es gerne wieder haben.

**Comment by carlobeltrame** [comment]
Navigation Maps sind noch da auf der Testplattform, siehe ganz unten: https://test.dialogluzern.ch
Bearbeiten kann man sie unter Einstellungen -> Startseite -> "Name" (die deutsche Übersetzung an diesem Ort ist fälschlicherweise "Name" statt "Navigation Maps").
