### ISSUE TITLE
Bild auf Startseite als HTML

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#106]
Wie viel Aufwand schätzt ihr, wenn wir das Bild auf der Startseite als HTML Teil umsetzen möchten? Ziel ist, dass der Schriftzug "Dialog" jeweils zentriert angezeigt wird und sich das Bild an das Gerät anpasst.

**Comment by carlobeltrame** [comment]
Ich würde das als CSS-Änderung umsetzen, was nicht sehr viel Aufwand ist (ca. 1 Stunde bis 1 halber Tag), vor allem wenn das Bild (oder zumindest die Abmessungen und die Position des Schriftzugs) in Zukunft gleich bleibt. Der HTML-Block wird dafür nicht gebraucht.

Wir müssten uns zuerst finden, was es genau bedeutet dass "sich das Bild an das Gerät anpasst". Das Bild ändert seine Skalierung ja bereits jetzt, je nach Bildschirmbreite. Wir haben aber die Möglichkeit, die Höhe der "Bildfläche" für beliebige Bildschirmgrössen anzupassen. Vielleicht könntet ihr Mockups (Skizzen oder gephotoshoppte Screenshots o.ä.) von verschiedenen Bildschirmgrössen mit dem gewünschten Look machen, und darin am besten gleich das finale Bild einbauen?

**Comment by Naadjjaa** [comment]
Das "Dialog" auf dem Bild ist ja kein Schriftzug sondern auch ein Bild. Geht das trotzdem mit CSS? Falls ja, könnt ihr das gerne auf INT mal zeigen. In welchem Format braucht ihr dazu das "Dialog" Bild? 

Ich würde sagen, wir kümmern uns erst mal um den "Schriftzug". Das mit den Bildschirmgrössen und dem Hintergrundbild können wir dann später anschauen.

**Comment by carlobeltrame** [comment]
Ach so, ich glaube ich habe dich falsch verstanden. Meinst du, wir sollen lieber das Foto und den Schriftzug nicht mehr in einem kombinierten Bild haben, sondern getrennt, sodass sie unabhängig voneinander skaliert / zentriert werden können? Dazu wäre dann tatsächlich der HTML-Block nötig.

Das Hintergrundfoto bräuchte ich dann wohl am einfachsten ungefähr in derselben Grösse wie es jetzt schon ist (nur halt ohne Schriftzug). Der Schriftzug selber wäre wohl als Vektorgrafik am praktischsten, sodass er beliebig gross und klein skaliert werden kann und trotzdem immer scharf angezeigt werden kann.

Wenn ihr uns diese beiden Komponenten liefern könnt wäre das schätzungsweise in 0.5 - 1 Tag Arbeit erledigt.

**Comment by innosmith** [comment]
@Naadjjaa: Wenn wir hierfür den HTML-Block nutzen müssen, können wir diesen später nicht mehr für anderes einsetzen. Als Bsp. habe ich auf https://boldideas.puzzle.ch/ den HTML-Block zum Einfügen des Sponsoring-Bildes auf der Startseite verwendet. @carlobeltrame zwei HTML-Blöcke auf der Startseite sind nicht möglich, korrekt?

**Comment by innosmith** [comment]
@carlobeltrame danke für den Vorschlag. Decidim Awesome wäre sicher offen für diese Erweiterung. Ich habe mich mit dem Entwickler ein paar Mal ausgetauscht; die haben viele spannende Ideen und arbeiten auch an einigen. Ich bespreche dies  morgen oder im Verlauf der Woche mit @Naadjjaa .

**Comment by carlobeltrame** [comment]
Ist erledigt, auf Produktion zu sehen. Die WAF hat noch versucht, mich daran zu hindern, das SVG einzubauen, ich war zuerst perplex wieso es lokal geht aber auf Produktion nicht... Aber gut zu wissen dass die WAF wirklich etwas macht.

Ich habe den "Hauptbild" Block rausgenommen, aber es ist wichtig dass das Bild dort drin hochgeladen bleibt, denn der HTML-Block zieht dieses Bild dann als Hintergrund an.

**Comment by carlobeltrame** [comment]
@innosmith Ausserdem habe ich gleich noch herausgefunden, wie man weitere HTML-Blöcke einfügen kann. Das System ist leider nicht darauf ausgelegt, "beliebig viele" von einem Typ von Block einzufügen, aber ich habe mal drei weitere HTML-Blöcke auf der Integration eingefügt. Falls ihr mehr braucht, einfach melden, es ist dann eine reine Copy-Paste-Deploy Sache.

**Comment by innosmith** [comment]
Auf dem Mac funktioniert es mit Chrome und Firefox. Mit Safari kommt das "Dialog" Bild nicht!

Auf Windows haben wir dieselben Probleme mit:
- Chrome Version 87.0.4280.141 (Offizieller Build) (64-Bit) auf Windows 10 Enterprise.
- Firefox Version 33.1 auf Phone 6, iOS 12.5.3

**Comment by carlobeltrame** [comment]
@innosmith Merci für den Report. Ich habe diese exakten Browser nicht zum testen, und auf einem frisch installierten Chrome auf Windows klappts bei mir. Aber ich habe jetzt noch etwas verbessert was die Kompatibilität erhöhen sollte. Kannst du nochmals probieren? Wenns nicht geht schau ichs mir am Montag mit einem Tool an, das ganz verschiedene Browser simulieren kann.

**Comment by innosmith** [comment]
Bei mir läuft es nun auf Safari auch, sehr gut. @Naadjjaa : bitte noch mit deinen Browsern testen.

**Comment by Naadjjaa** [comment]
@innosmith @carlobeltrame Funktioniert nun auch in meinen Browsern, danke!
