### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#107]
1. "Tritt der Veranstaltung bei" für die Anmeldung an einen Event ist leider kein Key. Könnt ihr das zu einem machen?

Ich würde es gerne übersetzen in "Melde dich für die Veranstaltung an"

2. Wenn bei einer Veranstaltung ein Bild als Anhang geladen wird, steht dann "ähnliche Bilder". Könnt ihr das auch zu einem Key machen?

Übersetzungsvorschlag: "dazugehörige Bilder"

**Comment by carlobeltrame** [comment]
Beide Übersetzungen hattet ihr bereits zuvor im Term Customizer angepasst, daher findest du sie nicht mit der Suchfunktion (die Suchfunktion sucht nur in den "original" Übersetzungen).
Die Keys sind `decidim.meetings.meetings.show.join` und `decidim.application.photos.related_photos`.
