### ISSUE TITLE
Feld nicht übermittelt

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#108]
In unserer Umfrage werden die Antworten des von Frage 5 abhängigen Feld 6 nicht übermittelt.
https://dialogluzern.ch/processes/dasprojekt/f/53/

**Comment by carlobeltrame** [comment]
Das scheint ein Bug zu sein, der auftritt, wenn man zwei Bedingungen für dieselbe Frage hat. Meine Hypothese ist, dass im Browser die Frage angezeigt wird, sobald nur eine der Bedingungen erfüllt ist, aber beim Speichern die Antwort nur berücksichtigt wird wenn alle Bedingungen erfüllt sind.

Als Workaround können wir die Bedingung umstellen auf "Frage anzeigen, wenn vorher NICHT mit Nein geantwortet wurde". Aber man kann diese Umfrage nur noch bearbeiten, wenn man sie auf "Unveröffentlicht" setzt, und dann gehen alle bisherigen Antworten verloren. @Naadjjaa kannst du die bestehenden Antworten zu dir herunterladen und dich dann nochmals hier melden, damit ich die Bedingung umstellen kann? (oder wenn du willst kannst du die Bedingung auch gleich selber umstellen)

**Comment by Naadjjaa** [comment]
Super, jetzt funktioniert es. Super Idee mit dem nicht-gleich. Als ich mich eingeloggt habe, waren die Antworten bereits verschwunden. Habt ihr sie exportiert?

**Comment by carlobeltrame** [comment]
Hm, nein, habe ich leider nicht... Vielleicht Anthony oder sonst jemand? Es waren ca. 5 Antworten wenn ich das richtig gesehen habe... Schlimmstenfalls könnten wir versuchen, die Antworten von Hand aus einem Datenbankbackup zu fischen.

**Comment by carlobeltrame** [comment]
Ich konnte die Antworten aus einem Datenbankbackup rekonstruieren, sende sie dir via Mail.
