### ISSUE TITLE
Bilder für Posts und Pages

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#11]
Der Editor kann grundsätzlich Bilder unterstützen in einer Grösse. Bei Decidim nachforschen. Wenn es etwas gibt eine Sache von 2-3h. Wenn es etwas noch nicht gibt selber machen 1-2 Tage.

**Comment by Kagemaru** [comment]
Etwas vorbereitetes gibt es weder von Decidim noch der Community.
Decidim benutzt [quill.js](http://quilljs.com/docs/modules/toolbar/) als Editor, dieser unterstützt nachträgliches Einfügen von Buttons in die Toolbar.
Daher wird es wohl auf Option 2 rauslaufen.

**Comment by bsantschi** [comment]
Offenbar gab es schon zwei Versuche, dieses Feature zu implementieren. Sie stiessen dabei bei Decidim auf offene Ohren, jedoch wurde es nach längeren Diskussionen dann doch nicht in aufgenommen (man möchte glaub noch auf den Upgrade auf Rails 6 warten).

Hier die Links:
- [Erster Versuch](https://github.com/decidim/decidim/pull/4595) aus dem 2018
- [Zweiter Versuch](https://github.com/decidim/decidim/pull/5364) aus dem 2019
- [Diskussion Rails 6 Upgrade](https://github.com/decidim/decidim/discussions/6550)

Lasst uns nächste Woche besprechen, ob wir hier einen eigenen Anlauf (Modul? PR?) nehmen wollen oder ob auch wir auf Rails 6 warten wollen/müssen.

**Comment by Kagemaru** [comment]
Nach Absprache haben wir entschieden, das Modul [Decidim Awesome](https://github.com/Platoniq/decidim-module-decidim_awesome/) einzubauen.

Momentaner Stand: Ich habe das Modul lokal getestet.

**Comment by innosmith** [comment]
Erste Tests mit Decidim Awesome sind sehr positiv! Im Backend fehlen im Menü noch deutsche Übersetzungen. Wir nutzen es noch etwas intensiver, dann tauchen vielleicht noch Änderungswünsche oder Fehler auf.
