### ISSUE TITLE
Veranstaltungen bei Organisation nicht chronologisch

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#113]
Unter Veranstaltungen im Hauptmenü sind Veranstaltungen neu chronologisch geordnet. 

Wenn Organisationen selber das Veranstaltungsmodul einsetzen, ist die Reihenfolge noch nicht chronologisch.

Siehe z.B. https://dialogluzern.ch/assemblies/stadtluzern/f/63/

**Comment by Naadjjaa** [comment]
@carlobeltrame Super, danke! Du kannst das gerne beim nächsten Deployment mitberücksichtigen!
