### ISSUE TITLE
Komponente hinzufügen geht nicht

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#117]
Safari: 9.1.2(11601.7.7)
Im Reiter Komponenten geht nichts auf, wenn die Backend-Userin auf "Komponente hinzufügen klickt".

**Comment by Kagemaru** [comment]
Ich kann dies im Safari 9 nachstellen. Allerdings hat dieser das letzte Mal im September 2016 ein Update erhalten.
Solch alte Browser unterstützen eine Vielzahl von Funktionen nicht, die auf einer modernen Seite eingesetzt werden.
Je mehr Versionen wir unterstützen, desto höher der Aufwand für alle Änderungen die wir machen, da sie weit zurück kompatibel sein müssen.

Ich würde empfehlen auf einen neueren Firefox und oder Chrome Browser zu wechseln, falls es kein neues Update für den Safari gibt.
