### ISSUE TITLE
Redirect Rules Server Fehler

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#120]
Siehe Screenshot führt ein Click auf die Redirect Rules im Backend (Menüpunkt zuunterst links) sowohl auf INT als auch PROD zu einem Server Fehler. Noch vor kurzem hat diese Funktion funktioniert?!

**Comment by innosmith** [comment]
![Screenshot 2021-05-31 at 17 33 24](https://user-images.githubusercontent.com/75796635/120215901-993f0a00-c236-11eb-8821-8a94f8b67501.png)

**Comment by carlobeltrame** [comment]
Dürfte dasselbe Problem sein wie https://github.com/puzzle/decidim-zuerich/issues/111

**Comment by Naadjjaa** [comment]
@carlobeltrame Ich benötige die Redirect Rules nächste Woche dringend! Es gibt einen Link, der bereits kommuniziert aber noch nicht installiert ist.

Ich komme zudem auch nicht mehr auf die Navbar Links 
https://dialogluzern.ch/admin/navbar_links

**Comment by Naadjjaa** [comment]
Funktioniert, gerne deployen. Danke! @carlobeltrame

**Comment by carlobeltrame** [comment]
Ist erledigt.

**Comment by innosmith** [comment]
Das passierte gerade während meiner Demo in Zürich 😉 Zum Glück konnte ich auf die Testplattform ausweichen.

LG Anthony

From: Nadja Ba ***@***.***>
Reply to: stadtluzern/decidim-ocl ***@***.***>
Date: Tuesday, 8 June 2021 at 16:22
To: stadtluzern/decidim-ocl ***@***.***>
Cc: Anthony Smith ***@***.***>, Author ***@***.***>
Subject: Re: [stadtluzern/decidim-ocl] Redirect Rules Server Fehler (#120)


Funktioniert, gerne deployen. Danke! @carlobeltrame<https://github.com/carlobeltrame>

**Comment by carlobeltrame** [comment]
Uff, sorry, davon wusste ich nichts. Ich frage eigentlich immer nach bevor ich deploye, aber Nadja hat zugesagt, da habe ich nicht länger überlegt
