### ISSUE TITLE
Swisstopo GIS-Daten

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#121]
In Abstimmung mit der GIS-Abteilung der Stadt Luzern möchten wir inbs. für die bislang weissen Bereiche ausserhalb des Stadtperimeters vorerst Kartenmaterial von Swisstopo verwenden.

Web Map Tiling Services WMTS: Verfügbare Dienste und Daten:  https://wmts.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml

Interessant wären wohl vor allem folgende beiden Dienste: SWISSIMAGE Hintergrund (Orthofoto) und Landeskarten (farbig)

Bitte vorerst auf INT als eigene Layers verfügbar machen, damit wir vergleichen und testen können.

**Comment by carlobeltrame** [comment]
Grobschätzung: 0.5 PT

**Comment by carlobeltrame** [comment]
Ich habe hier möglicherweise noch leicht zu viel versprochen: Es ist technisch nicht möglich, gleichzeitig die Layers vom GIS LU und von swisstopo anzuzeigen, weil die Zoom-Levels zwischen den beiden nicht kompatibel sind. GIS LU verwendet Zoom-Levels zwischen 0 und 9 (siehe Levels [hier](https://svc.geo.lu.ch/main/rest/services/basis/basis_citymap_baspla/MapServer)), swisstopo verwendet für vergleichbar aufgelöste Zoom-Stufen Levels zwischen 14 und 28 (siehe Tabelle [hier](https://api3.geo.admin.ch/services/sdiservices.html#gettile)). Je nach Zoom-Levels muss ich bei der Karten-Anzeige ein unterschiedliches Koordinatensystem angeben, und die Karten-Anzeige (Leaflet) unterstützt mehrere Koordinatensysteme gleichzeitig schlicht nicht.

Ich habe daher jetzt mal die städtischen Karten auf der Integration ganz durch swisstopo ersetzt, sollte zum Testen ja ausreichen. Es gibt aber noch einen Bug der verhindert dass die Layers überhaupt angezeigt werden, muss ich mir nächste Woche noch anschauen... Lokal hats einwandfrei funktioniert...

**Comment by innosmith** [comment]
Die Luftbildaufnahmen von Swisstopo sehen sehr gut aus. Bei der schematischen Darstellung gefallen uns - wo vorhanden - die GIS-Luzern Daten besser. Aber ausserhalb des Stadtperimeters eben keine Daten, insofern nicht die bessere Lösung. @carlobeltrame: Ist es möglich, dass die Luftbildaufnahmen von Swisstopo jeweils die Default-Karte sind und bei Bedarf auf die schematische von Swisstopo gewechselt wird?

**Comment by carlobeltrame** [comment]
Ja, sobald ich es hinkriege dass die swisstopo-Karten auch wirklich angezeigt werden wird es sich genau so verhalten.

**Comment by carlobeltrame** [comment]
Wie es aussieht funktionieren die swisstopo-Karten auch auf der Testumgebung, siehe zum Beispiel hier: https://test.dialogluzern.ch/meetings
Das Problem mit den weissen Karten tritt nur auf der Startseite auf, und ich vermute es hat mit der dortigen Karte "Was läuft in meinem Quartier" zu tun. Bevor ihr diese auf Produktion einsetzen möchtet, müssten wir also diese Wechselwirkung noch untersuchen und einen Fix finden. Aber für den Moment sehe ich dieses Ticket hier als abgeschlossen an.

**Comment by innosmith** [comment]
@carlobeltrame : bitte die mögliche Wechselwirkung auf der Startseite INT mit leerer Kartenanzeige als neues Ticket aufnehmen. Die Quartierkarte wird demnächst auf PROD kommen.
