### ISSUE TITLE
Sentry-Integration (Automatisch alle Links überprüfen, ob sie zu Serverfehler führen)

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#124]
- manuelle Frontend-Tests (keine Unit-Tests)
- INT Umgebung (mit Login)
- PROD Umgebung (ohne Login)

**Comment by carlobeltrame** [comment]
Ich habe mich hierzu noch etwas ausgetauscht mit anderen Leuten bei Puzzle die schon ähnliches gemacht haben. Vom Ansatz "sämtliche Links einmal durchklicken", speziell wenn man eingeloggt ist, wurde mir abgeraten. Grund ist, dass auf einer Webseite auch vereinzelt Aktionen (nicht nur Navigation) durch klicken auf Links ausgeführt werden, z.B. das "Befürworten" eines Vorschlags oder je nach dem sogar der Logout-Link. Zwar gibt es Richtlinien für Webseiten-Entwickler, dass man gefahrlose Aktionen eher durch Links darstellt und Aktionen mit Nebenwirkungen als Buttons oder Formulare, aber wir haben weder eine Garantie dafür, dass das in decidim durchgängig so umgesetzt ist, noch dass es in Zukunft auch so bleibt. Eine "Blacklist" / "Denylist" von Links die nicht angeklickt werden sollen ist erfahrungsgemäss auch keine befriedigene Lösung, da bei decidim Updates und neuen Modulen neue "gefährliche" Links auftauchen können. Eine "Whitelist" / "Allowlist" hingegen löst euer Problem mit toten Links in User-Inhalten nicht.

Aufgrund dieser Schwierigkeit würde vorschlagen, die beiden Anforderungen doch wieder zu trennen:
* Fürs Monitoring von 500er-Serverfehlern müssten wir einfach mal die bereits eingerichtete Sentry-Anbindung flicken. Sentry ist ein Tool das wir bei Puzzle einsetzen um genau solche Serverprobleme zu sammeln und zu tracken. Die Entwickler bekämen dann z.B. ein Mail wenn für irgendeinen User (auf Test- und Produktionsumgebung) ein 500er Serverfehler auftritt. Aufwand das zum fliegen zu bringen: 2PT.
* Für die toten Links in den Inhalten würde ich menschliche Moderatoren empfehlen, aber wenn ihr es wirklich automatisieren möchtet könnten wir hier wohl doch einen Crawler einrichten, der ohne Login auf der Produktionsumgebung herumklickt, aber nur in ganz bestimmten Bereichen der Seite: Die Inhalte die von Usern abgefüllt werden. Aufwand wegen Unsicherheit und Einbindung in die Infrastruktur: 4-6PT

**Comment by bsantschi** [comment]
Entscheid: wir setzen "nur" Sentry um. Puzzle übernimmt die Aufwände.

**Comment by Kagemaru** [comment]
Funktioniert nun auf INT & PROD:
https://sentry.puzzle.ch/pitc/decidim-luzern/issues/45241
