### ISSUE TITLE
Decidim Update v0.25

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#126]
Sobald produktiv freigegeben, auf v0.25 upgraden. Idealerweise noch vor dem geplanten Pen-Test Ende Q3/2021.

**Comment by bsantschi** [comment]
Siehe: https://github.com/puzzle/decidim-zuerich/issues/149

**Comment by bsantschi** [comment]
Wurde im Rahmen von https://github.com/stadtluzern/decidim-ocl/issues/205 umgesetzt.
