### ISSUE TITLE
Mehr Komponenten sichtbar machen

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#128]
Siehe Bsp. Screen im Projekt "Dialog Luzern - das Projekt" werden ab einer gewissen Anzahl - oder allenfalls wenn zu breit? - die hintersten Menüpunkte einer Organisation oder Prozesses in ein Submenü "Mehr ..." verbannt und sind damit nicht mehr sichtbar, obwohl auf dem Bildschirm genügend Platz wäre. Liesse sich dies einfach verbessern?

**Comment by innosmith** [comment]
![Screenshot 2021-06-16 at 11 29 10](https://user-images.githubusercontent.com/75796635/122195387-9e3ac500-ce96-11eb-9734-f1ec197d9d4b.png)

**Comment by carlobeltrame** [comment]
Dieses Feature ist natürlich dafür da, dass dieses Menü auf möglichst vielen Bildschirmgrössen gut aussieht. Aber bereits jetzt ist es möglich, dass auf gewissen Bildschirmgrössen die Breite nicht ausreicht:
![Screenshot from 2021-06-16 11-55-36](https://user-images.githubusercontent.com/7566995/122199276-30909800-ce9a-11eb-9417-c7a7063677f7.png)

Wenn euch egal ist, dass das auf mehr Bildschirmen passiert, und je nach dem die Komponenten sogar auf mehr als zwei Zeilen verteilt werden, können wir das Limit der angezeigten Komponenten z.B. auf 100 erhöhen (Standard ist 5, plus das erste, fixe Tab). Das "Mehr" Menü wird dann nicht mehr angezeigt. Aufwand dafür ist ca. 0.5PT.

Tech Notes:
Entweder https://github.com/decidim/decidim/blob/develop/decidim-participatory_processes/app/views/layouts/decidim/_process_navigation.html.erb überschreiben und beim Aufruf von `extended_navigation_bar` als zweites Argument 100 übergeben, oder den Helper selber überschreiben https://github.com/decidim/decidim/blob/1b131d3b0e805b9bf314788a48e95dfca0ae69d1/decidim-core/app/helpers/decidim/layout_helper.rb und den Standardwert von 5 auf 100 ändern.

**Comment by innosmith** [comment]
Ich schlage vor, dass wir auf 10 erhöhen, bevor der "Mehr ..." Button erscheint. @Naadjjaa wie siehst du das?

**Comment by Naadjjaa** [comment]
Finde ich gut. @carlobeltrame Gerne umsetzen.

**Comment by Naadjjaa** [comment]
Auf Handy standardmässig zugeklappt

**Comment by carlobeltrame** [comment]
Habe das umgesetzt und auf Integration aufgeschaltet. Das mit dem Handy ist anscheinend ein Bug der nur auf Mobilgeräten auftritt. Wenn ich den Browser gleich schmal mache ist das Menü eingeklappt. Da ich das Menü nicht fix einklappen, sondern nur "umschalten" kann, mache ich das jetzt als Workaround wenn die Bildschirmbreite schmal ist. Bitte wenn möglich mit verschiedenen Handys und Tablets in Hochformat und Querformat testen.

**Comment by innosmith** [comment]
Auf Mac mit Google Chrome, Safari und Firefox ok. Gleiches Verhalten: Das Menü klappt sich zu, sobald das Fenster eine gewisse Breite unterschritten hat. Auf dem iPhone mit Safari sieht man immer nur den ersten Menüpunkt mit zugeklapptem Menü. Falls der Benutzende versteht, dass dies ein Menüpunkt ist und mit dem Dreieck rechts aufgeklappt werden kann, alles i.O.

![IMG_AFB7B7103818-1](https://user-images.githubusercontent.com/75796635/129542479-952695ad-3077-41a4-bbe8-79af26954351.jpeg)

@Naadjjaa : bitte weitere Tests machen, falls du noch andere Geräte/Softwarekombination hast wie Windows und Android.
