### ISSUE TITLE
Prozessdokumentation im Wiki erstellen (Ticket Workflow, Aufwandschätzungen, Labels, Deployments, ...)

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#131]

**Comment by bsantschi** [comment]
Ich habe einen ersten Entwurf unter https://github.com/stadtluzern/decidim-ocl/wiki erstellt. Bitte ergänzen/korrigieren. Die "Labels" habe ich noch nicht dokumentiert, da diese in der Zusammenarbeit noch nicht erprobt sind (zum Beispiel entstand das Label "bitte umsetzen" letzte Woche spontan, ich bin aber der Meinung, dass wir darauf verzichten könnten und auch dieser Status in den Spalten abbilden können).

**Comment by innosmith** [comment]
Besten Dank @bsantschi . Ich habe erste Ergänzungen gemacht.

**Comment by Kagemaru** [comment]
Ich habe noch den Developer Workflow hinzugefügt. Ich weiss nicht ob wir das noch verschmelzen wollen.

Eigentlich finde ich diese Gliederung recht gut:
* Allgemeine Spalteninformationen
* Workflow für Anthony/Nadja
* Workflow für Developer

**Comment by innosmith** [comment]
Eigentlich war die Idee, eine Prozess-Doku zu erstellen und nicht zwei mehr oder weniger redundante Dokus. Wenn es entlang der Prozess Unterschiede gibt zwischen Fachseite und Dev könnte man dies innerhalb eines Prozess-Schrittes kennzeichnen.

**Comment by Kagemaru** [comment]
@innosmith Ich habe dies noch angepasst.
@carlobeltrame Stimmt der Prozess so für dich, oder fehlt noch was?
