### ISSUE TITLE
403 Fehler hübscher (Text folgt)

### ISSUE THREAD

**Issue by Kagemaru** [stadtluzern/decidim-ocl#133]

**Comment by Kagemaru** [comment]
Ich habe hier mal ein schnelles Design für die Fehlermeldung erstellt. Lässt sich auch einfach anpassen. Wenn möglich keine Bilder oder wenn Bilder, nur einfache, da wir sie direkt in die Seite einbetten müssen.

Bevor ich weitere Anpassungen mache warte ich auf das Feedback von @Naadjjaa.

https://codepen.io/Kagemaru/full/QWvLLMx

**Comment by Naadjjaa** [comment]
Danke dir @Kagemaru 

- Könnest du alle Meldungen noch in die DU-Form "übersetzen"?
- 403 ist die Fehlermeldung, wenn die WAF greift, oder? Dann würde ich hier schreiben: "Der Zugriff auf diese Seite ist dir nicht gestattet. Bitte melde dich für eine Überprüfung deiner Zugriffsrechte unter info@dialogluzern.ch."
- bei allen ausser 502 und 503 zusätzlich ebenfalls auf die Kontaktaufnahme an info@dialogluzern.ch ergänzen: "Wärst du so nett, uns kurz zu beschreiben, welche Schritte du vor dem Fehler ausgeführt hast? Du erreichst uns unter info@dialogluzern.ch". Oder spricht etwas dagegen?
- Ist das Oooooops... nicht englisch? Ich würde stattdessen schreiben: "Uups!"

**Comment by Kagemaru** [comment]
Ich habe diese Änderung mal auf INT gepushed:

<html>
<body>


400.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Kein Zugriff</title>   </head>   <body>     <h1>       Uups! Der Server sagt, du hast keinen Zugriff auf diese Seite.<br>       Falls dies ein Fehler ist, melde dies bitte an       <a href="mailto:info@dialogluzern.ch">info@dialogluzern.ch</a>.     </h1>   </body> </html>
-- | --
403.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Kein Zugriff</title>   </head>   <body>     <h1>       Uups! Der Zugriff auf diese Seite ist dir nicht gestattet.<br>       Bitte melde dich für eine Überprüfung deiner Zugriffsrechte unter       <a href="mailto:info@dialogluzern.ch">info@dialogluzern.ch</a>.     </h1>   </body> </html>
404.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Nicht gefunden</title>   </head>   <body>     <h1>Seite konnte nicht gefunden werden.</h1>     <h1>       Uups! Diese Seite konnte nicht gefunden werden.<br>       Falls dies ein Fehler ist, melde dies bitte an       <a href="mailto:info@dialogluzern.ch">info@dialogluzern.ch</a>.     </h1>   </body> </html>
500.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Applikationsfehler</title>   </head>   <body>     <h1>       Uups! Auf dem Server ist ein Fehler aufgetreten       und eine Meldung wurde an uns gesendet.<br>        Falls dieser Fehler länger besteht kannst du uns unter       <a href="mailto:info@dialogluzern.ch">info@dialogluzern.ch</a>       erreichen.     </h1>   </body> </html>
502.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Temporärer Unterbruch</title>   </head>   <body>     <h1>Habe bitte einen Moment Geduld. Wir sind gleich wieder da.</h1>   </body> </html>
503.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Temporärer Unterbruch</title>   </head>   <body>     <h1>Habe bitte einen Moment Geduld. Wir sind gleich wieder da.</h1>   </body> </html>


</body>
</html>

**Comment by innosmith** [comment]
@Kagemaru bitte wie folgt anpassen:
404: nur die zweite Zeile mit "Uups! ..."
500: erhaltet ihr nun wirklich eine Info und wer reagiert darauf? Falls dies prozessual noch nicht durchgängig umgesetzt ist, würde ich die user darum bitten, uns auf info@dialogluzern.ch den Fehler direkt zu rapportieren.

**Comment by innosmith** [comment]
@Kagemaru : wurden diese letzten Änderungswünsche am Freitag mit auf PROD deployed?

**Comment by Kagemaru** [comment]
> 500: erhaltet ihr nun wirklich eine Info und wer reagiert darauf?

@innosmith Ja, das wird im Sentry (Issue #124) gesammelt. Die Fehlermeldungen werden gleichzeitig mit Sentry / AntiVirus ausgerollt.
Ich kann vorerst trotzdem mal den Text anpassen. Wie findest du diesen Vorschlag?

<html>
<body>


Fehlercode | Ausgabe 
-- | --
500.html | <!DOCTYPE html> <meta charset="UTF-8"> <html>   <head>     <title>Dialog Luzern – Applikationsfehler</title>   </head>   <body>     <h1>      Uups! Auf dem Server ist ein Fehler aufgetreten.<br>Bitte melde dies an <a href="mailto:info@dialogluzern.ch">info@dialogluzern.ch</a>.      </h1>   </body> </html>

</body>
</html>

**Comment by innosmith** [comment]
@Kagemaru : danke, Textvorschlag passt.

**Comment by innosmith** [comment]
@Kagemaru : die Text-Änderungen müsstest du bei Bedarf testen. Wir können diese einfach nur freigeben für die PROD.
