### ISSUE TITLE
ungewollter PROD Release nachgehen

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#134]

**Comment by Kagemaru** [comment]
Der Build war geplant, aber das Tagging des Images ist fälschlicherweise passiert. Das Script, welches ich verwende hat dies automatisch bei einem vollen Build ausgelöst. Ich habe dies nun angepasst.

Ich empfehle ausserdem einen Stable Branch auf dem Repo einzuführen, um Code Promotion bei einem rebuild des Images zu vermeiden.
