### ISSUE TITLE
Fehlende Übersetzung Backend

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#135]
Im Backend ist im Menü zuunterst links noch eine fehlende Übersetzung, welche wir mit dem Term-Customizer nicht machen können. 

Bitte den Textschlüssel "de.decidim.url_aliases.admin.menu.url_aliases" anpassbar machen.

**Comment by carlobeltrame** [comment]
Ich verstehe nicht, warum die Übersetzung nicht funktioniert, aber wenn ihr mir den Text gebt der da stehen soll, kann ich das einfach fix in unserem Repository eintragen. Denke das wollt ihr ja wahrscheinlich selten ändern.

**Comment by innosmith** [comment]
Die deutsche Label-Bezeichnung ist "URL Aliases", gleich wie in der englischen Version.

**Comment by innosmith** [comment]
Funktioniert, danke. Ready für PROD.
