### ISSUE TITLE
Dringend (bis Ende Woche): Bug Geolocation bei Vorschlagerstellung

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#143]
Wenn die Geolocation bei einem Vorschlag von Hand verschoben wird, fällt dieser beim Speichern raus. Wir möchten am Freitag mit einem entsprechenden Projekt live gehen.

**Comment by Naadjjaa** [comment]
https://user-images.githubusercontent.com/75797851/125453608-abfc5a37-28c7-44e9-8dce-3ddb0e23af0d.mp4

**Comment by Naadjjaa** [comment]
@Kagemaru @carlobeltrame Danke fürs Beheben bzw. Ursachenabklärung.

**Comment by carlobeltrame** [comment]
Ich habe das Problem gefunden und sollte heute Nachmittag einen Fix umsetzen können.

Technische Erklärung:
Die Eingabefelder werden auf der "Sie können den Punkt auf der Karte verschieben." Seite versteckt wiederholt (als hidden inputs), aber die Checkbox `has_address` fehlt unter diesen versteckten Feldern. Wenn ich es schaffe, dieses Feld hinzuzufügen, ist der Fehler behoben. Ich konnte das bereits verifizieren indem ich den hidden input von Hand in den Browser Dev Tools hinzugefügt habe.

**Comment by Naadjjaa** [comment]
@carlobeltrame Perfekt, danke!

**Comment by carlobeltrame** [comment]
Das Problem wurde übrigens bei Decidim bereits vor 21 Tagen [gefixt](https://github.com/decidim/decidim/pull/8160) aber noch nicht released. Ich habe den offiziellen Fix bei uns übernommen.
Da die Testumgebung durch die Arbeit am Antivirus besetzt ist (und das Ausrollen dort gerade nicht auf Anhieb funktioniert), würde ich das nach sorgfältigem lokalem Testen gleich auf Produktion deployen, wenn das für dich okay ist @Naadjjaa.

**Comment by Naadjjaa** [comment]
@carlobeltrame Ja, das passt :)

**Comment by carlobeltrame** [comment]
Ist jetzt deployed, gemäss meinen Tests funktionierts. Bitte testen und ggf. Ticket schliessen.

**Comment by Naadjjaa** [comment]
Funktioniert, danke!
