### ISSUE TITLE
Nutzung Initiativmodul führt zu Server-Fehler

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#148]
Bitte auf der Testumgebung das Initiativmodul https://docs.decidim.org/en/admin/initiatives/ aktivieren. 

Via Decidim Awesome Menü Hacks werden wir den Menüpunkt zuerst auf INT und auf PROD (sobald auch dort deployed) unsichtbar machen, um das Modul noch besser kennenlernen zu können und dann Pilot-Initiativen zu starten.

Solange im "stealth-mode", müssen wir allenfalls weitere Content-Areas wie "Letzte Aktivitäten" entfernen, damit auch dort keine Links auf noch nicht freigegebene Initiativen sichtbar und clickbar werden.

Bitte rasch auf INT deployen, damit wir es per nächsten Dienstag 17.08. mit einer Gruppe von Anwendern diskutieren können.

**Comment by carlobeltrame** [comment]
Ist auf Integration ausgerollt.

**Comment by Naadjjaa** [comment]
@franbuehler Ich werde von der WAF am Erfassen von Initiativen gehindert. Könnt ihr da was machen?

**Comment by bsantschi** [comment]
Hoi @Kagemaru kannst du dir das anschauen oder soll ich Fränzi "aufbieten"?

**Comment by Kagemaru** [comment]
@bsantschi Ja, da muss Fränzi ran. Ich kann momentan die Striktheit der WAF reduzieren, aber das Problem lösen muss Fränzi.

**Comment by franbuehler** [comment]
Hallo @Naadjjaa, @Kagemaru und @bsantschi,
Entschuldigt bitte, ich hatte übersehen, dass ich getagged wurde. Es war keine Absicht.
Chattet, mailt oder pingt mich sonst jeweils über einen anderen Kanal noch an, wenn ich nicht antworte.
Ich schaue es mir jetzt an.

**Comment by franbuehler** [comment]
Hallo @Naadjjaa,
Könntest du bitte erneut testen und mir den Zeitraum deiner Tests nennen?
Ich sehe WAF Warnings, die jedoch nicht zu Blockierungen geführt haben. 
Geschaut habe ich auf der Produktion und Integration.
Danke und LG, Fränzi

**Comment by bsantschi** [comment]
Hoi Anthony @innosmith, könntest du [das](https://github.com/stadtluzern/decidim-ocl/issues/148#issuecomment-904705953) während Nadjas Ferien übernehmen?

**Comment by franbuehler** [comment]
Hallo zusammen,
Ich habe mir den Fehler heute angesehen und es ist definitiv kein WAF Fehler.
Die Fehlermeldung und die Logs zeigen einen Error 500 - Internal Server Error.
Die WAF würde mit einer HTTP Response 403 oder 400 blockieren.
Ich habe jedoch den Zeitpunkt und den HTTP Fehler 500 in den Logs gefunden.
Weiter habe ich einen Error im Rails Pod gefunden, der genau um diesen Zeitpunkt passiert ist. 
Um August 27th 2021, 10:34:03.005, falls ihr euch das genauer ansehen möchtet. 
Aber so wie es aussieht, seid ihr dem Fehler schon auf der Spur.

**Comment by carlobeltrame** [comment]
Das Problem hat mit scopes (Bereichen, nicht areas / Gebieten) zu tun.
Ohne gross zu durchschauen wie das Ganze zusammenspielt, habe ich im Admin-Backend beim Initiativen-Typ "Stadtideen" zuunterst bei "Bereiche für den Typ der Initiative" einen Bereich erfasst. Im Frontend im Neue-Initiative-Formular wird dadurch keine Bereichs-Auswahl mehr angezeigt, und der Fehler tritt (vordergründig) nicht mehr auf.

**Comment by innosmith** [comment]
@carlobeltrame : beim Versuch, dies auf der Testplattform zu rekonstruieren, führt es zumindest bei mir weiterhin zu einem 500er. Ich habe bei der Stadtidee den Scope geändert und den Initiativtyp aktualisiert. Im Frontend neue Initiative erstellt und auf dem zweiten Screen kann ich zwar keinen Scope wählen, die Dropdown bleibt aber sichtbar. Beim Versuch fortzufahren kommt der 500er. Any ideas?

**Comment by carlobeltrame** [comment]
Wenn du den Scope im Initiativtyp unverändert lässt funktioniert es. Leider kann man das nur mit technischen Tricks zurückändern, und man kann auch keinen Initiativtyp löschen.
@innosmith Plant ihr denn überhaupt, die Scopes bei Initiativtypen zu nutzen? Wenn ich da Zeit investieren soll, das zu beheben muss ich mich erst einlesen und -denken, das dauert dann zusammen mit dem Fix schon gut mal 1-1.5 Tage.

**Comment by innosmith** [comment]
Wir testen es einmal mit diesen Einschränkungen. Idealerweise werden Probleme damit bei Meta-Decidim gemeldet.
