### ISSUE TITLE
User Registrierung führt zu Fehlerseite

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#159]
Siehe Attachment folgt nach der Registrierung eines neuen Users auf PROD via "Registrieren" anstelle einer Erfolgsseite eine Fehlerseite. Der User wurde aber erfolgreich erstellt, eine Email zugesandt.

Fehlerzeitpunkt: Mo 27.09.2021, Zeit 12:34

![Screenshot 2021-09-27 at 12 34 08](https://user-images.githubusercontent.com/75796635/134893136-bd21fc41-95d2-47d4-87b6-2bb11c1eb5ae.png)

**Comment by carlobeltrame** [comment]
Ich kann das weder auf der Testumgebung noch auf der Produktionsumgebung reproduzieren:
![Screenshot from 2021-10-01 14-26-10](https://user-images.githubusercontent.com/7566995/135619556-748c7d47-5a5f-468c-9307-f7eff2ba4a97.png)

Ich habe jeweils die Terms&Conditions akzeptiert, und die Checkbox für Kontakterlaubnis deaktiviert. Auf der Testumgebung habe ich danach im Dialog den rechten Button geklickt, auf der Produktionsumgebung den linken.
@innosmith ich gebe dir via E-Mail eine Möglichkeit, beliebig viele Accounts zu erstellen um das erneut nachzustellen.

**Comment by carlobeltrame** [comment]
Aufgrund der URL in deinem Browser-Screenshot mit /admin/officializations?... könnte ich mir vorstellen, dass es bei dir folgendermassen abgelaufen ist:

1. Du warst am Morgen als Plattform-Admin eingeloggt, und warst auf der Teilnehmerliste (https://dialogluzern.ch/admin/officializations) und hast nach "anthony" gefiltert
2. Deine Session lief über den Mittag ab (Fehlerzeitpunkt ist 12:34 wie du schreibst)
3. Du kamst nach dem Mittag zurück zum Browser und hast mit der Registrierung begonnen
4. Nach der Registrierung wird man direkt als der neue User eingeloggt
5. Nach dem Login nach abgelaufener Session oder Permission Denied leitet einen Decidim an den letzten Ort an dem man vorher war
6. Dein neuer User hatte keinen Zugriff auf die Teilnehmerliste, darum bekamst du einen 404 Fehler

Könnte das der Grund sein?

**Comment by innosmith** [comment]
nach Rücksprache einmaliges problem.
