### ISSUE TITLE
Fehlermeldung bei Erstellen eines Events aufgrund der Adresse

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#16]
![Adresse bei erstellen Events](https://user-images.githubusercontent.com/75797851/103626113-0aa2b700-4f3c-11eb-8f1f-87f6102a5b29.PNG)

Immer wenn ich versuche einen Event zu erstellen, bekomme ich eine Fehlermeldung - siehe Screenshot. Ich habe schon viele Varianten versucht, die Adresse einzugeben. Keine funktioniert.

**Comment by Kagemaru** [comment]
Aus Erfahrungen mit Quartieridee, haben wir den gleichen Prefix für Luzern übernommen.
Für Luzern ist allerdings ein anderer Prefix auf OpenStreetMap valide.
