### ISSUE TITLE
Key für ersten Reiter in Projekt und Organisation

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#162]
Ich finde für das Wort Information, den ersten Reiter in jedem Projekt keinen Key. Falls dieser erstellt werden kann, gerne. Ansonsten bitte Standardmässig in allen Projekten (process) das Wort Informationen mit Übersicht ersetzen.

**Comment by Naadjjaa** [comment]
![image](https://user-images.githubusercontent.com/75797851/136509304-f1ede53d-ca72-4c82-b575-5068639e1de7.png)

**Comment by carlobeltrame** [comment]
Grund ist dass ihr die Übersetzung selber schon auf "Informationen" überschrieben habt. Original-Übersetzung war "Der Prozess", der Key ist `de.layouts.decidim.process_navigation.process_menu_item`. Damit solltest du es selber ändern können.
