### ISSUE TITLE
In Proj. und Org. die Navigation standardmässig ausgeklappt bei mobile Nutzung.

### ISSUE THREAD

**Issue by bsantschi-zz** [stadtluzern/decidim-ocl#179]

**Comment by Kagemaru** [comment]
Konnte ich nicht nachstellen auf:
- [ ] Chrome on iPhone 13 Pro Max (Browserstack)
- [ ] Safari on iPhone 13 Pro Max (Browserstack)
- [ ] Firefox on ROG Phone II (Mein Telefon)

@bsantschi Bei welchem Browser/Telefon ist dir dies aufgefallen?

**Comment by carlobeltrame** [comment]
Die Idee war, dass das Menü neu standardmässig ausgeklappt sein soll. Ich habe das in https://github.com/stadtluzern/decidim-ocl/commit/df00512101ad937b29914652e50cab5c3669cd97 umgesetzt und auf Integration ausgerollt.

**Comment by Naadjjaa** [comment]
Getestet. Funktioniert, merci!
