### ISSUE TITLE
"Help Sections" führt zu Fehler

### ISSUE THREAD

**Issue by carlobeltrame** [stadtluzern/decidim-ocl#18]
Wenn im Backend bei den Settings auf den Menüpunkt "Help Sections" navigiert wird, führt das zu einem Fehler.

**Comment by carlobeltrame** [comment]
Das ist anscheinend ein Bug im Calendar Modul. Wurde [hier](https://github.com/decidim/decidim/issues/6466) bereits gemeldet und am 8. September [gefixt](https://github.com/alabs/decidim-module-calendar/pull/25).
Ich habe eine neuere Version des Kalender-Moduls installiert und konnte lokal bestätigen dass das Problem nicht mehr auftritt. Sobald wir wieder auf INT deployen können wird das Problem behoben sein.

**Comment by innosmith** [comment]
Auf ocl-test läuft es jetzt fehlerfrei. Auf PROD muss es dann noch nachgezogen werden.
