### ISSUE TITLE
Bot Registration vermeiden

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#183]
@Naadjjaa und ich beobachten eine starke Zunahme von Bot-Registration auf der produktiven (öffentlichen) Plattform.

Seitens Decidim gäbe es eine Erweiterung mit Frage für Humans, entwickelt von OpenSourcePolitics, siehe https://github.com/OpenSourcePolitics/decidim-module-question_captcha. 

Gibt es alternative/weitere Ansätze, um Bot Registrationen zu reduzieren? Z.b. mittels der WAF?

**Comment by franbuehler** [comment]
Hallo @innosmith 
Ich schaue mir die WAF Möglichkeiten an und gebe meine Erkenntnisse dem Team weiter.

**Comment by franbuehler** [comment]
Das CoreRuleSet (CRS) kann Bots/Crawlers anhand des HTTP Headers User-Agent erkennen, nicht aber an deren Verhalten oder gar ein Chaptcha verwenden.

Das CRS hat folgende drei User-Agent Regeln - Paranoia Level (PL) steht hinten:

# 913100 - security scanners (data file scanners-user-agents.data) - PL1
# 913101 - scripting/generic HTTP clients (data file scripting-user-agents.data) - PL2
# 913102 - web crawlers/bots (data file crawlers-user-agents.data) - PL2

Quellcode der Rules:
https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-913-SCANNER-DETECTION.conf#L24

Ich denke, vor allem Rule 913102 auf PL2 ist interessant.
Entdeckt werden folgende User-Agents:
https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/crawlers-user-agents.data

**Comment by Naadjjaa** [comment]
Siehe auch: https://meta.decidim.org/processes/roadmap/f/122/proposals/15628?filter%5Bactivity%5D=all&filter%5Bcategory_id%5D%5B%5D=&filter%5Borigin%5D%5B%5D=&filter%5Brelated_to%5D=&filter%5Bscope_id%5D%5B%5D=&filter%5Bsearch_text%5D=spam&filter%5Bstate%5D%5B%5D=&filter%5Bstate%5D%5B%5D=accepted&filter%5Bstate%5D%5B%5D=evaluating&filter%5Bstate%5D%5B%5D=state_not_published&order=recent

**Comment by carlobeltrame** [comment]
Konkret sind in diesem Meta Decidim Post folgende bereits gemergeten PRs erwähnt:
https://github.com/decidim/decidim/pull/6696 (Nutzende reporten, zusätzlich zum Kommentar reporten das bisher existierte)
https://github.com/decidim/decidim/pull/6804 (Nutzende blocken)
https://github.com/decidim/decidim/pull/6941 (Metriken / Graphen über die Anzahl geblockte Nutzende etc.)
Diese Features müssten glaube ich alle bereits auf Dialog Luzern installiert sein.

Der Teil "Automate the ban of spamming users" wurde soweit ich sehe nicht umgesetzt, weil man sich noch nicht auf "Regeln" einigen konnte anhand denen man legitime von illegitimen Accounts / Registrationen etc. erkennt. Ein vorgeschlagener rudimentärer Ansatz wäre die bereits in Decidim vorhandene Komponente "rack-attack" zu nutzen, um zu blockieren wenn z.B. mehr als 10 Anfragen pro Sekunde eingehen. Aber im Metadecidim-Post sehe ich niemand der das konkret umgesetzt hat.

**Comment by bsantschi** [comment]
Bitte @carlobeltrame Modul auf INT aufschalten und testen: https://github.com/OpenSourcePolitics/decidim-module-question_captcha

**Comment by carlobeltrame** [comment]
Um das Modul zu installieren muss ich auf decidim 0.24.4 updaten (aktuell 0.24.3). Dabei habe ich Probleme mit dem modul decidim-module-jitsi-meetings. Nutzt ihr das noch? Auf der Produktion sehe ich diese Seite: https://dialogluzern.ch/processes/dasprojekt/f/48/

Leider dauert es etwas länger, das Sicherheitsfragen-Modul zu installieren, wenn ich zuerst die Probleme mit dem Jitsi-Modul lösen muss.

**Comment by innosmith** [comment]
@Naadjjaa : wollen wir kurzfristig Jitsi ersetzen und anstelle einen MS Teams Link verwenden? Im Rahmen des Decidim-Updates könntest du dann erwähnen, dass Jitsi nach Upgrade-Kompatibilität auf 0.24.3 wieder kommt.

**Comment by innosmith** [comment]
@carlobeltrame : bitte Jitsi temporär ausschalten, damit du rasch ein Upgrade auf Decidim v0.24.3 machen kannst inkl. Installation Captcha-Modul. Ich frage nach bez. Upgrade-Plänen seitens Jitsi. Nadja hat eben grünes Licht gegeben.

**Comment by carlobeltrame** [comment]
Ich habe einen Weg gefunden wie ich Jitsi behalten konnte. Das ist jetzt auf der Integration aufgeschaltet. Aber um es zu testen müsst ihr wohl kurz die Registrierungen im System Dashboard aktivieren.

**Comment by innosmith** [comment]
Danke @carlobeltrame : System Dashboard auf INT ist angepasst. Entweder mache ich einen Nutzungsfehler oder das Captcha funktioniert noch nicht vollständig. Nach Ausfüllen aller Felder beim Sign-up erscheint das Formular nach Absenden erneut, jedoch ohne Captcha. Wenn ich dann das neue PW erneut eingebe, kommt nach Absenden wieder der Original-Screen mit Captcha. Eine Neuregistrierung schaffe ich demzufolge aktuell nicht. Any ideas?

<img width="1359" alt="Screenshot 2022-02-02 at 00 00 40" src="https://user-images.githubusercontent.com/75796635/152066206-4087cfdb-2b6f-4d6b-a9c6-db79719a3b4d.png">

Im zweiten Screenshot ist ersichtlich, dass ein modales Fenster mit zweimal den gleichen Textbuttons kommt. Hier müssen wir noch etwas verbessern beim "Sign Up".

Wie ich gesehen habe, lassen sich die Captcha-Texte mit Term-Customizer anpassen.

**Comment by carlobeltrame** [comment]
Ja, das Modul scheint noch Probleme zu haben. Ich konnte mich zwar erfolgreich auf der Testplattform registrieren, aber nur wenn ich von Anfang an alles richtig gemacht habe. Wenn ich z.B. ein zu kurzes oder zu triviales Passwort eingebe, oder eine falsche Antwort auf die Sicherheitsfrage gebe, komme ich zurück auf das Registrierungsformular, nur dass dann die Sicherheitsfrage ganz fehlt. Ich kann das sowohl auf INT wie auch lokal bei mir so reproduzieren.
Ich schaue mir mal an, wie das Modul programmiert ist und schaue ob wir einen Fix machen können. Ein Bug-Report beim Modul wäre wohl so oder so angebracht.

**Comment by carlobeltrame** [comment]
Übrigens, die zwei Texte "Keep unchecked" sind nur auf Englisch dieselben. Die Übersetzungs-Keys dafür sind:
`decidim.devise.shared.newsletter_modal.buttons.check`: Kontakterlaubnis erteilen und fortfahren
`decidim.devise.shared.newsletter_modal.buttons.uncheck`: Ohne Kontakterlaubnis fortfahren

**Comment by carlobeltrame** [comment]
Ich habe zwei Probleme im Modul gefunden und in https://github.com/OpenSourcePolitics/decidim-module-question_captcha/pull/17 als Verbesserungsvorschlag angebracht. Es sieht aus als wäre dieses Modul noch nicht sehr praxis-erprobt, abgesehen vom happy path (User gibt beim ersten Versuch alles richtig ein) und offensichtlichen sad path (User gibt alles ausser die Sicherheitsfrage richtig ein).

Vorab mal, es ist erwartetes Verhalten, dass die Sicherheitsfrage nicht mehr auftaucht nachdem man sie einmal richtig beantwortet hat, und zwar für 10 Minuten (Dauer wäre konfigurierbar).
Dass du auf das Registrierungsformular zurückkamst muss an anderen Fehleingaben im Formular gelegen haben. Zum Beispiel überprüft Decidim dass das Passwort nicht zu ähnlich ist wie der Username. Beim Testen verwenden wir oft triviale Usernamen und Passwörter wie "test", da passiert es leicht dass Decidim das mal abweist. Da du die Sicherheitsfrage richtig beantwortet hast, ist diese dann erst mal nicht mehr aufgetaucht. So weit hat noch alles so funktioniert wie es sollte.

Beim zweiten Absenden des korrigierten Formulars jedoch klappte es mit dem Modul nicht mehr wegen einem Überlegungsfehler. Konkret merkte sich das Modul nicht deine alte korrekte Antwort. Das ist der erste Fehler den ich behoben habe.

Der zweite Fehler ist, dass die Einstellungen (unsere deutsche Sicherheitsfrage) nicht richtig respektiert wurden, was zu einem Endlos-Loop beim abrufen der verfügbaren Fragen führen konnte.

Beides habe ich jetzt mal in einer Puzzle-Kopie (Fork) des Moduls gefixt, von dort aus die Verbesserungen den Modul-Maintainern angeboten, und diese Kopie statt das originale Modul auf der Integration deployed. Sobald die Verbesserungen beim Modul akzeptiert wurden, können wir auch wieder auf den offiziellen Stand des Moduls wechseln.

Übrigens war der Maintainer des Moduls heute dran, es für decidim 0.25 fit zu machen, das wird uns also hoffentlich nicht blockieren wenn die anderen Module so weit sind.

**Comment by innosmith** [comment]
Besten Dank @carlobeltrame . Dann teste ich es noch einmal. Übrigens was das verwendete Testpasswort schon etwas schwieriger als "test" ;-) Die Anpassungen für v0.25 habe ich mit meiner Anfrage bei Armand (Lead Dev) getriggert. Ich halte den aktuellen Stand zu allen Modulen im Zürcher Ticket fest.

**Comment by innosmith** [comment]
@carlobeltrame, @Naadjjaa  : Mit der richtigen Captcha Antwort kam ich jetzt rein und war direkt als Dummy-User eingeloggt. Hier fehlt noch ein double opt-in mit Email-Verifikation. Aber das können wir nicht so schnell lösen und ich habe in den System-Einstellungen auch keine passende Option gefunden. Ebenso gibt es auch kein Modul, welches nur hierfür geschaffen wäre.

Mit der falschen Captcha Antwort kam ich nicht weiter. Habe ca. 6 mal eine falsche Antwort eingegeben und kam immer und immer wieder zurück, eine richtige Antwort eingeben zu können. Das passt soweit und stoppt einfache Bots vermutlich erfolgreich.

Lasst es uns auf PROD probieren!

**Comment by innosmith** [comment]
@Naadjjaa : bitte auf PROD und ev. auch auf INT die Sprach-Keys noch ins Deutsche übersetzen. Siehe dazu auch ein Hinweis oben von Carlo.

**Comment by carlobeltrame** [comment]
Klar, ist schon angepasst. Soll ich das gleich heute nochmals deployen? Oder braucht ihr nochmals Vorlaufzeit um die Nutzenden zu warnen?

**Comment by Naadjjaa** [comment]
Kannst deployen :)

**Comment by carlobeltrame** [comment]
Erledigt
