### ISSUE TITLE
CSS neu mit Decidim Awesome

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#184]
Wir möchten gerne die CSS-Änderungen direkt mit Decidim Awesome machen können. Bitte die CSS-Styles nach Decidim Awesome übertragen.

**Comment by Kagemaru** [comment]
Folgende CSS Regeln können (momentan) nicht übertragen werden:
- `.leaflet-control-layers .leaflet-control-layers-toggle { background-image: url(...) }`
  - [Wird von der WAF geblockt, siehe Ticket #185
- `.leaflet-control-layers .leaflet-control-layers-toggle { background-image: url(...) }`
  - Rails füllt den Pfad der `layers.png` ein
- `.leaflet-retina .leaflet-control-layers .leaflet-control-layers-toggle { background-image: url(...) }`
  - Rails füllt den Pfad der `layers-2x.png` ein
- `#highlighted-assemblies .card__image-top { background-image: url(...) }`
  - Rails füllt den Pfad der `organization-default-image.png` ein

@carlobeltrame Kann man die Bilder eventuell statisch hinterlegen und referenzieren?

**Comment by carlobeltrame** [comment]
Ich kenne keinen einfachen Weg ausser base64-encoding, und das ist für grosse Bilder nicht geeignet...
Zwar wird beim bundeln ein Manifest geschrieben, das Assets auf ihre gebundelten Pendants mappt und umgekehrt: https://dialogluzern.ch/assets/.sprockets-manifest-bb6ec3b68d5c291cc361166d20083c88.json
Aber dieses Manifest selber hat auch einen Hash im Namen, also sogar wenn wir mit Decidim Awesome irgendwie dieses Manifest interpretieren könnten wüssten wir wegen dem noch nicht wo es überhaupt liegt.

@innosmith konkret bedeutet das, überall wo ihr grosse Bilder via CSS einsetzen wollt (von den aktuellen vor allem das organization-default-image.png), müssen wir das weiterhin mit Code-Änderungen machen. Oder falls ihr diese Bilder irgendwo auf dem Internet verfügbar machen könnt könnte man sie auch ohne Code-Änderung im Decidim Awesome CSS ansteuern.

**Comment by Kagemaru** [comment]
@carlobeltrame
Spricht denn etwas dagegen, das Bild direkt in /public abzuspeichern und per nginx auszuliefern?
Dann kann man es unter https://test.dialogluzern.ch/organization-default-image.png verwenden.
```
#highlighted-assemblies .card__image-top {
  background-image: url('organization-default-image.png');
}
```

Ich habe es mal testweise direkt in den nginx gepackt. Beim nächsten Deployment fliegt es wieder raus. Wenn es so ok ist, kann ich die Bilder dort hinterlegen.

**Comment by carlobeltrame** [comment]
Stimmt, das sollte auch funktionieren. Aber dennoch brauchts dafür halt ein Deployment wenn das Bild mal ausgetauscht werden soll oder ein neues Bild an einem neuen Ort benötigt wird.

**Comment by Kagemaru** [comment]
Klar, dafür sind dann alle CSS Anpassungen ausser die @font-faces im Decidim Awesome und können auch gescopet werden. Um die Deployments kommen wir nicht rum.

**Comment by innosmith** [comment]
@Kagemaru , @carlobeltrame : danke für die Inputs. Vorläufig haben wir keinen spez. Web-Server, wo wir solche Bilder speichern könnten. Entsprechend würde ich die "nginx" Variante nutzen, sodass wir ein WAF freundliches CSS nutzen können. Das Defaultbild wird selten ändern. 

@Kagemaru bitte das WAF-Log wieder von GitHub entfernen, merci. Security-Themen bitte über sep. Kanäle kommunizieren.

**Comment by Kagemaru** [comment]
Die Bilder sind nun direkt im /public ordner und werden aus Decidim Awesome referenziert.
Das layers icon habe ich auch gleich umgewandelt und dort abgelegt.
