### ISSUE TITLE
Veranstaltungsübersicht. Anzeige der Organisation.

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#190]
![image](https://user-images.githubusercontent.com/75797851/152557667-0107595e-f913-48cf-862c-070376ba6855.png)
Ich werde die Zuweisung entfernen bis ihr das gefixt habt (also nicht extrem dringend).

**Comment by Naadjjaa** [comment]
@bsantschi Ich denke das ist eine einfache Änderung (!?) Habe gesehen, dass sich "" in den Code eingeschlichen haben.

**Comment by carlobeltrame** [comment]
Tritt vermutlich seit dem minor Upgrade auf 0.24.3 auf.

**Comment by carlobeltrame** [comment]
Habe das auf Integration gefixt. Leider hindert mich die WAF daran, die Verbindung von einem Assembly zu einem Prozess (z.B. Neugestaltung Tribschengasse) herzustellen. @Kagemaru @franbuehler wolltet ihr das im Admin-Backend nicht ausschalten?

Ich habs dann von Hand getestet indem ich intern ein Assembly mit einem Prozess verbunden habe (ohne an der WAF vorbei zu müssen), mit dem Befehl `Decidim::Assembly.last.link_participatory_space_resources([Decidim::ParticipatoryProcess.find(31)], "included_participatory_processes")`.

Auf der Veranstaltungsübersicht hats dann auf Anhieb geklappt. Auf der Startseite bei den Blogposts gibts noch die weitere Hürde, dass die Blogposts stark gecached werden. Ich habe es auch dort von Hand verifiziert indem ich das Cache abgeräumt habe, aber falls du es testest @Naadjjaa musst du vermutlich einen neuen Blogpost verfassen damit sich an der Anzeige auf der Startseite irgendetwas ändert.

**Comment by Kagemaru** [comment]
@carlobeltrame
Wir blocken nach und nach einzelne Regeln weg auf der /admin Route, die wir nicht auf anderem Wege sinnvoll entfernen können. Wir haben nicht die ganze WAF für die /admin Route ausgeschaltet.

Bei mir hat es beim letzten Test funktioniert, vielleicht mache ich auch was falsch.
Eventuell wurde es mit dem Fix für #191 auch gleich repariert.

Wir können es morgen zusammen testen, wenn du willst
