### ISSUE TITLE
Bug: Startseite Blogs html

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#199]
Tritt nur auf, wenn der Ursprung ein Projekt ist (process). Eventuell wurde der Bug damals nur für den Ursprung Organisation (assembly) gemacht?

**Comment by Naadjjaa** [comment]
![image](https://user-images.githubusercontent.com/75797851/165244083-800e8d5e-5e50-4e5d-8260-edab2a45e342.png)

**Comment by Kagemaru** [comment]
Ich konnte dieses Verhalten auf der Integration nicht nachstellen. Hast du mir einen Tipp, wie es bei dir auftritt?

Das ursprüngliche Ticket war hier: #190
Dies ist bis jetzt nur auf der Integration ausgerollt. In der Produktion hatten wir seit 3 Monaten kein Relelase.

**Comment by Naadjjaa** [comment]
@Kagemaru Gibt es einen Grund, weshalb hier nichts mehr gelaufen ist?

**Comment by bsantschi** [comment]
Wir möchten noch #201 #202 flicken und danach ein Päckli mit allen Fixes deployen, okay für dich?

**Comment by Naadjjaa** [comment]
@bsantschi Ja, wenn das zeitnah klappt. Bisher hat sich noch niemand beschwert betr. dem html Fehler auf der Startseite aber sieht halt schon nicht schön aus.
