### ISSUE TITLE
Modul "Initiatives" aktivieren

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#20]
Kann es sein, dass wir das Modul Initiatives nicht aktiv haben? Falls ja, bitte aktivieren. Ich würde es gerne testen.
https://github.com/decidim/decidim/tree/master/decidim-initiatives

**Comment by carlobeltrame** [comment]
Das ist korrekt. Ich habe das Modul jetzt im Code installiert. Wir haben leider gerade noch ein Problem, welches uns davon abhält die Änderung auf der Testumgebung auszurollen. Sobald dieses Problem behoben ist werden die Initiatives verfügbar sein.

**Comment by Naadjjaa** [comment]
Aktuell brauchen wir die Funktion nicht siehe #64
