### ISSUE TITLE
Fehlermeldung bei Verbergen von Komponente

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#210]
PROD: Beim Verbergen der Komponente Vorschläge in der Organisation Smart City Luzern Nord erhalte ich eine Fehlermeldung.¨

INT: In einem Test auf Int. funktioniert das.

**Comment by Naadjjaa** [comment]
https://user-images.githubusercontent.com/75797851/171334337-245962a7-e95c-422e-86ed-19f175227007.mp4

**Comment by bsantschi** [comment]
Vermutung: Datenfehler (ein Feld, das möglicherweise nicht ausgefüllt wurde oder eine Validierung fehlschlägt).

**Comment by innosmith** [comment]
Ich habe unter "Generelle Einstellungen" der Vorschlagskomponente "Ideen einbringen" die Option "Bereiche aktiviert" neu deaktiviert. Damit funktioniert das Aktualisieren der Informationen und dementsprechend auch das Rückgängig machen der Veröffentlichung.
