### ISSUE TITLE
Bestehende Veranstaltungen lassen sich nicht bearbeiten.

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#216]
Auf PROD - Organisationen - Stadt Luzern lassen sich einzelne Veranstaltungen nicht mehr bearbeiten.

Uups! Auf dem Server ist ein Fehler aufgetreten.
Bitte melde dies an info@dialogluzern.ch.

Zum Beispiel: Komponente Grosser Stadtrat #359
26. Sitzung des Grossen Stadtrates von Luzern vom 30. Juni 2022

**Comment by carlobeltrame** [comment]
Ich konnte das Problem finden und direkt lösen. Die Veranstaltungen lassen sich nun wieder bearbeiten.
