### ISSUE TITLE
Dokument-Links funktionieren nicht

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#217]
Hochgeladenen Dokumente werden korrekt angezeigt und lassen sich öffnen. Wenn hingegen ein Direktlink zum Dokument versendet oder verlinkt werden soll, funktioniert dieser Link nicht. Könnte das an der aktuellen Umstellung liegen?

Beispiel PROD: Ergebnisse Forum I:
https://dialogluzern.ch/processes/kulturagenda2030

hier in Blog verlinkt:
https://dialogluzern.ch/processes/kulturagenda2030/f/306/posts/109

**Comment by Naadjjaa** [comment]
![image](https://user-images.githubusercontent.com/75797851/177974144-24c4b431-19ab-4e17-bdd3-3c167a71cff6.png)

**Comment by Naadjjaa** [comment]
<img width="954" alt="fehler" src="https://user-images.githubusercontent.com/75797851/177974247-16310e3b-9f99-4813-a6a3-f2b34f6da1e2.png">

**Comment by bsantschi** [comment]
Liebe Nadja, du hast einen internen Link kopiert und  seit dem Upgrade (und dem Wechsel auf Storage S3) greift hier ein Security-Feature, das den Zugriff auf interne Links nur ein paar Minuten erlaubt.

Bitte kopiere im Original-Link die Adresse, die mit dialogluzern.ch beginnt (und nicht ocp4-pitc-stlu-decidim-prod). Klicke dazu am einfachsten mit der rechten Maustaste auf den Link und klicke auf "Link kopieren" und verwende diesen Link.

![copylink](https://user-images.githubusercontent.com/108862416/178433340-2cd7bf64-5698-4996-84ec-1cf83b930c4a.png)
