### ISSUE TITLE
Titelbild nicht mehr verknüpft

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#219]
Zum Wecheln des Titelbildes musste ich früher bei der Org. Stadt Luzern die Datei Titelbild austauschen. Ich habe das gestern gemacht, dennoch bleibt das alte Bild bestehen.

**Comment by carlobeltrame** [comment]
Das Bild kann mit der neuen Speicherlösung leider nicht mehr mit unserem alten Workaround einfach geändert werden, und es wird auch in Zukunft irgendwann mal nicht mehr angezeigt werden wenn wir es so lassen wie bisher. Um das Bild zu ändern musst du neu:
1. Das neue Bild wie bisher unter Einstellungen -> Aussehen -> Highlighted Inhaltsbanner Bild hochladen und speichern
2. Zu "Aktuelles Bild" scrollen und Rechtsklick aufs Bild -> Bild-URL kopieren
3. Die URL bei Startseite -> HTML-Block auf der ersten Zeile einfügen, zwischen den Klammern bei `background-image:url(...)`. **Vorsicht**: hier keine Tippfehler machen, sonst ist die Homepage kaputt. Neu sollte es ungefähr so aussehen: `...style="background-image:url(https://dialogluzern.ch/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUFDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b4201637a9735167ec7cd7d8b5171a20623a6569/0864-IMG_0073-5_zuge.jpg)">`

**Comment by Naadjjaa** [comment]
Funktioniert. Ich habe es allerdings mit einem Org. Anhang umgesetzt. Den Highlight Banner möchten wir anders einsetzen können.
