### ISSUE TITLE
Website URL für Assemblies

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#22]
Website URL für Assemblies analog Facebook-Link hinzufügen. Damit kann eine Organisation neben ihrer Präsenz auf OCL einfach auf ihre Website verlinken, d.h. eine URL muss in einem neuen Browser-Fenster geöffnet werden können.

Grafisch ist die Website URL im Bereich Facebook-Verlinkung rechts hinzuzufügen. Ansicht UI einfach, bedingt Backend-Anpassung. Das Feld wird im Frontend nur angezeigt, wenn auch Inhalt vorhanden ist.

**Comment by Kagemaru** [comment]
Um ein weiteres Feld bei den bestehenden Sozialen Netzwerken hinzuzufügen, muss man ein Modul erstellen.

**Comment by Kagemaru** [comment]
Todo: Vorschlag bei Decidim einreichen.

**Comment by Kagemaru** [comment]
Vorschlag erstellt: https://meta.decidim.org/processes/roadmap/f/122/proposals/16316

**Comment by innosmith** [comment]
Mal schauen, wie sich der Vorschlag entwickelt.
