### ISSUE TITLE
INT: Das Hinzufügen eines Übersetzungssets im Term Customizer führt zu Fehlermeldung

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#220]
Request Entity Too Large
The requested resource does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

**Comment by Naadjjaa** [comment]
Soeben gesehen: Auch das umbenennen eines bestehenden führt zu diesem Fehler

**Comment by Naadjjaa** [comment]
Auf PROD funktioniert beides.

**Comment by carlobeltrame** [comment]
Kannst du es nochmals probieren? Thomas hat jetzt noch die Erweiterung der erlaubten Grösse von Imports auf Luzern INT nachgeholt.

Ich habe zudem gesehen dass du wieder in die UTF-8-Probleme gelaufen bist. Als Reminder hier nochmals:
- Encoding fürs CSV beim Speichern in Excel muss zwingend Unicode / UTF-8 sein (oder was immer am ähnlichsten heisst in Excel). Du hattest bisher das Encoding ISO-8859-1 verwendet, was in Westeuropa üblich ist, aber nicht für globale verwendete Software wie Decidim geeignet ist.
- Separator (Trennzeichen) darf nicht Komma sein, sondern muss ein Semikolon `;` sein
- Als Delimiter (Anführungszeichen) muss ein normales doppeltes Anführungszeichen verwendet werden: ". Das ist wies aussieht standardmässig schon so bei Excel.
