### ISSUE TITLE
Initiativmodul aktivieren

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#224]
Könnt ihr bitte einschätzen, mit wie viel Aufwand ihr das Initiativmodul wieder zum laufen bringt? Es handelt sich um ein Core-Element und ich kann mir nicht vorstellen, dass dieses nicht mit den aktuellen Versionen kompatibel ist.

**Comment by Naadjjaa** [comment]
@bsantschi Ich wäre froh, wenn dieser Task noch vor meinen Ferien am 20.10. angegangen werden könnte. So könnte ich die Texte nochmals final vorbereiten und während meiner Abwesenheit durch die KOMM prüfen lassen.

**Comment by Kagemaru** [comment]
@Naadjjaa Ich habe noch sichergestellt, dass unsere fixes für die Initiativen drin sind.

Eine aktualisierte Version ist nun auf INT.
