### ISSUE TITLE
Assembly Seite individuell benennen können

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#23]
Innerhalb einer Assembly können beliebig Komponenten hinzugefügt werden und deren Titel in der Navigation frei gewählt werden. Schön wäre es, wenn Assemblies den Titel für die allgemeinen Informationen z.B. zum Quartierverein ebenfalls selber betiteln könnten. Als Bsp. die Abkürzung ihres Vereins, "Home" oder vergleichbare Titel. Falls der Aufwand zur Umsetzung dieses Features zu gross ist, lassen wir es sein und definieren einen passenden Titel für alle Assemblies, als Bsp. "Organisation" anstelle "Gremium", siehe Screenshot.

**Comment by innosmith** [comment]
![Screenshot 2021-01-17 at 21 48 52](https://user-images.githubusercontent.com/75796635/104855762-ed43f480-590e-11eb-9c23-e3f7385bdf09.png)

**Comment by innosmith** [comment]
Vielleicht könnt ihr dies als Textvariable für uns mittels "Term Customizer" selber ändern lassen; oder noch einfacher, wenn z.B. Vereine den Titel selber festlegen können, wie oben beschrieben.

**Comment by Kagemaru** [comment]
Möglichkeiten in der Reihenfolge der Einfachheit:
- Die Übersetzung für alle anpassen
  - Einfach
  - In der Translation oder per Term Customizer anpassen
  - key: `de.layouts.decidim.assembly_navigation.assembly_menu_item`
- Die Übersetzung für alle individuell, aber fest setzen
  - Etwas schwieriger
  - File _assembly_navigation.html.erb ersetzen, dort variable translation keys setzen
  - In der Translation oder per Term Customizer anpassen
  - key: `de.layouts.decidim.assembly_navigation.assembly_menu_item_<assembly slug>`
- Die Übersetzung selbst anpassbar umsetzen
  - Schwierig
  - Benötigt meiner Meinung nach ein eigenes Modul, zusätzliche Datenbankfelder und Input Felder im Adminbereich

Vieleicht hat @carlobeltrame  noch eine zündende Idee dazu.

**Comment by innosmith** [comment]
So oder so werden wir übergreifend für alle einen neuen Begriff mittels Term Customizer festlegen, danke für den Key. Bitte ändert es dahingehend, dass wir per Term Customizer zusätzlich pro Assembly individuell einen anderen Text festlegen können bei Bedarf. @Naadjjaa zur Info.

**Comment by Kagemaru** [comment]
Todo:
- Template patchen
- de.layouts.decidim.assembly_navigation.assembly_menu_item_<assembly slug> als Translation Key
- Default Translation als Fallback
- Im Term Customizer benennen
