### ISSUE TITLE
PDF Modul/Komponente von Pokecode einbauen und aktivieren

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#236]

**Comment by Naadjjaa** [comment]
Hierzu brauche ich ebenfalls eine Offerte.
Besten Dank

**Comment by bsantschi** [comment]
Gerne erstellen wir dazu eine Offerte. Rückfragen per E-Mail an Nadja gesendet.

**Comment by bsantschi** [comment]
Bitte PDF Modul/Komponente von Pokecode im Rahmen des Upgrades auf Decidim v0.27.3 installieren und aktivieren.

**Comment by bsantschi** [comment]
Nadja schaut, dass wir es am Donnerstag 13. August einbauen können.

**Comment by carlobeltrame** [comment]
@Naadjjaa hast du schon etwas von Pokecode gehört? Am Code haben sie zuletzt vor 2 Tagen etwas geändert.

**Comment by Naadjjaa** [comment]
@carlobeltrame Siehe E-Mail.

**Comment by Naadjjaa** [comment]
@carlobeltrame Pünktlich ready:

gem 'decidim-participatory_documents'
After installing the gem they need to install migrations:
bundle
bundle exec rails decidim_participatory_documents:install:migrations
bin/rails db:migrate

**Comment by Naadjjaa** [comment]
@carlobeltrame Sorry, I forgot a little update on the deploy instructions (you'll find it in the README file in Github as well):

These are the steps required to install it:
bundle
bundle exec rails decidim_participatory_documents:install:migrations
bundle exec rails decidim_participatory_documents:install_pdf_js
bundle exec rails db:migrate

**Comment by carlobeltrame** [comment]
Das erneute Integrationsrelease ist durch. Ich konnte das Modul nicht testen weil ich keine Ahnung habe was es macht oder wie man es bedient.

**Comment by Naadjjaa** [comment]
Hallo Carlo. Danke dir. Ich kann die Komponente leider gar nicht auswählen, um sie zu testen.
@microstudi any idea why I can not chose the component after we installed the module?


![Image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/d920c2ce-872a-4425-8fbf-d83e2cd97e3c)

**Comment by bsantschi** [comment]
Hoi Nadja, ich vermute, dass Carlo gestern das Upgrade rückgängig machen musste, da mehrere Sachen (insb. Winterthur) nicht mehr funktionierten. Möglicherweise reicht es heute (vor Carlos Ferien) nicht mehr die Probleme in den Griff zu kriegen und einen neuen Release zu machen. Carlo oder ich halten dich auf dem Laufenden.

**Comment by Naadjjaa** [comment]
@bsantschi Danke für die Info. Ihr könnt jederzeit auch gerne direkt auf Pokecode zugehen falls es am Modul selbst liegt.

**Comment by paarals** [comment]
Hi!
Happy to help if you need anything!

El dv., 14 de jul. 2023, 10:46, Nadja Ba ***@***.***> va
escriure:

**Comment by Naadjjaa** [comment]
@Kagemaru Danke! Falls das auch überhaupt schon testable ist: 

- Die deutschen Übersetzungen werden bei mir nicht angezeigt
- Ich erhalte eine Fehlermeldung beim Hochladen einer PDF Datei

![Image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/0c181238-628c-422d-9780-b8386707778d)

**Comment by Naadjjaa** [comment]
@Kagemaru: Die Deutschen Übersetzungen fehlen noch. Da wir wohl noch andere Bugs beheben müssen, dies einfach als Reminder für später. Muss nicht sofort geschehen. (Ausser es könnte Einflüsse auf die Bugs haben?)

**Comment by Naadjjaa** [comment]
@Kagemaru 
Hier müsste ein PDF zu sehen sein: https://test.dialogluzern.ch/admin/participatory_processes/updatenvb/components/805/manage/documents/edit_pdf?id=2

**Comment by Naadjjaa** [comment]
@Kagemaru Hier noch mehr Infos von Ivan: The server needs to returns a specific header allowing the content to be served in iframes. If using Amazon AWS, this is configured in the bucket properties. Other providers have similar tools. It is usually called CORS configuration.

**Comment by Naadjjaa** [comment]
@Kagemaru Eine Funktion, die wir für das PDF Modul gebaut haben ist in der aktuellen Version auf INT noch nicht vorhanden. Gemäss Nachfrage bei Pokecode müsste dies aber der Fall sein, wenn ihr die neuste Version eingebaut hättet. gem 'decidim-participatory_documents', git: "https://github.com/openpoke/decidim-module-participatory-documents".

**Comment by carlobeltrame** [comment]
@Naadjjaa ich brauche bei Modul-Bugs sehr viel genauere Schritt-für-Schritt-Beschreibungen, wie ich das Problem nachstellen kann. Kannst du mir angeben, auf welcher Seite du was geklickt hast? Kann ich dasselbe auch mit meinem Account nachstellen?

**Comment by Naadjjaa** [comment]
@carlobeltrame  Entschuldige, hier noch ein Versuch:

Im Frontend kann der eingeloggte User sobald er mindestens einen Kommentar zum Dokument gemacht hat, diesen als Excel Export herunterladen. Siehe Video. 


https://github.com/stadtluzern/decidim-ocl/assets/75797851/d841cf66-f5bd-4938-9c1c-75b283c7e324

**Comment by carlobeltrame** [comment]
@Naadjjaa schon mal gut, merci. Aber ich weiss auch nicht, wie ich überhaupt ein PDF hochladen kann und zum kommentieren freigeben kann. Kannst du mir den Link schicken, wo du deine Tests machst?

**Comment by carlobeltrame** [comment]
Ich habe jetzt dein Testprojekt gefunden. Dort drin kann ich aber nicht einmal einen neuen Kommentar posten (was ich müsste, um dein Problem nachzustellen). Da musst du aber Pokecode anfragen, was da das Problem sein könnte.

https://github.com/stadtluzern/decidim-ocl/assets/7566995/0279b682-90a2-4bb9-b072-694e84e202e1

**Comment by Naadjjaa** [comment]
@carlobeltrame Sehr komisch. Bei mir kommt der Fehler auch. Allerdings hat es gestern noch funktioniert. Vielleicht weil diese Module vor dem Update erstellt wurden? Wenn ich jedenfalls die Komponente frisch hinzufüge, klappt das bei mir wieder:. Bei dir? https://test.dialogluzern.ch/processes/carlo/f/822/ --> hier ein Testlink. Habe mit zwei unterschiedlichen Nutzern bereits getestet.

**Comment by Naadjjaa** [comment]
@carlobeltrame Soeben herausgefunden: Die Fehlermeldung kommt bei weniger als 5 Zeichen.

**Comment by carlobeltrame** [comment]
Stimmt, merci. Bei Pokecode's Version sieht die angezeigte Fehlermeldung aber besser aus (und eigentlich wichtig: sie sieht anders aus).
Jetzt wo ich das Problem mit dem Export ungefähr nachstellen kann (bei mir kommt zwar eine andere Fehlermeldung als bei dir), ist der nächste Schritt dass ich mich in den Code von Pokecode vertiefe, um herauszufinden, wo etwas schief gehen könnte. Dazu komme ich leider erst Anfang nächste Woche.

**Comment by Naadjjaa** [comment]
@carlobeltrame Danke Carlo. Ich bin froh, wenn du es zeitnah angehen kannst, damit das mit dem Prod Release am Mittwoch klappt. Falls du am Montag etwas dringendes von mir brauchst, bitte per Handy melden. Schicke die Nr. per Mail nochmals.

**Comment by bsantschi** [comment]
Die WAF meldet invalides JSON im Request body bzw. ein zu frühes EOF.

**Comment by carlobeltrame** [comment]
@Naadjjaa das WAF-Problem konnte inzwischen behoben werden. Für mich funktioniert nun der Export, wenn ich Kommentare gemacht habe. Wenn ich keine Kommentare gemacht habe, kommt immer noch eine Fehlermeldung, aber diesmal liegts nicht an der WAF sondern vermutlich an Modul-Code.
