### ISSUE TITLE
OCL Sprache DE, ohne EN im Frontend

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#26]
Wir möchten gerne im Frontend die Sprachauswahl zumindest für die nächsten Monate wegnehmen lassen und deutsch als Standardsprache festlegen. Die meisten Content-Lieferanten, Stadtverwaltung inkl., werden bis zum geplanten Start nicht alle Texte auch übersetzen können. Würden wir dann die Sprachauswahl belassen, könnte es zu diversen Supportanfragen führen. Im Backend bez. Sprachen alles belassen wie es ist.

**Comment by Kagemaru** [comment]
Hierzu muss ich mich noch mit @carlobeltrame absprechen. Ich sehe momentan keine Möglichkeit dies nur im Frontend zu deaktivieren. Zumal man auch mit `?locale=de` die Sprache ändern kann und eine automatische Auswahl der Sprache durch Erkennung der Browsersprache erfolgt.

**Comment by bsantschi** [comment]
Mündlich besprochen und im Rahmen von #53 bereits umgesetzt.
