### ISSUE TITLE
Decidim 0.23

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#27]
Macht es Sinn, noch vor dem OCL-Launch auf Decidim 0.23 zu erhöhen? Welche Vor- und Nachteile bringt uns dies in der aktuellen Phase vor dem Launch per Ende Feb/Anfang März?

**Comment by Kagemaru** [comment]
Hier sieht man die Änderungen von v0.22.0=>v0.23.0=>v0.23.1: https://github.com/decidim/decidim/releases

**Comment by innosmith** [comment]
Im Bereich Maps gibt es u.a. Änderungen, von welchen wir ebenfalls betroffen sein könnten. @carlobeltrame hat hier im September 2020 Änderungen gemacht für die GIS-Kartenintegration von Luzern. Seht ihr allfällige negativen Folgen, welche dafür sprechen, dass wir vor dem Go-Live auf ein Upgrade auf die aktuellste Version verzichten?

**Comment by innosmith** [comment]
Wir haben es im Team kurz besprochen. Bitte auf die neueste Version 0.23.1 aktualisieren.

**Comment by carlobeltrame** [comment]
Das Modul [decidim-plans](https://github.com/mainio/decidim-module-plans) ist nicht kompatibel mit decidim 0.23. Wie möchtet ihr vorgehen? Wie wichtig ist dieses Modul für euch? Kann ich es entfernen um das Upgrade zu machen?

**Comment by innosmith** [comment]
Gibt es weitere Inkompatibilitäten? Ansonsten warten wir lieber noch etwas zu, bis Module wie decidim-plans kompatibel sind. Aktuell haben wir noch keinen dringenden Bedarf für das Upgrade.

**Comment by carlobeltrame** [comment]
Ausser plans scheint auf den ersten Blick alles kompatibel zu sein. Das Jitsi-Modul war offiziell auch noch nicht mit 0.22 getestet, auf dieselbe Art wie wir es 0.22-fähig gemacht haben habe ich es für 0.23 angepasst. Und beim Term Customizer steht eine [vorgeschlagene triviale Aktualisierung](https://github.com/mainio/decidim-module-term_customizer/pull/46) noch aus, da konnte ich einfach den Vorschlag übernehmen.

An decidim-plans wurde zuletzt im Oktober gearbeitet, im November hat der Maintainer ein [Issue](https://github.com/mainio/decidim-module-plans/issues/44) beantwortet demzufolge es ihm bewusst ist dass der aktuellste Stand des Moduls bei 0.22 zu Problemen mit der API führen kann. Auf dem Modul steht "Development of this gem has been sponsored by the City of Helsinki", es ist daher unklar ob und wie bald das aktualisiert wird. Ich werde den Fehler der mit 0.23 auftritt sicher noch reporten.

Die andere mittelgrosse Änderung für 0.23.1 die ich bereits ausgeführt habe ist es, die Karten-Anbindung an die [neuen Karten-Konfigurations-Möglichkeiten](https://github.com/decidim/decidim/releases/tag/v0.23.0) in decidim anzupassen. Ich werde von daher mal den Zwischenstand auf GitHub hochladen, sodass wir da weitermachen können sobald ihr grünes Licht gebt.

**Comment by innosmith** [comment]
Besten Dank für die Prüfung. Habe es eben mit @Naadjjaa besprochen. In dem Fall entscheiden wir uns für den Upgrade und warten nicht auf das Upgrade von Plans. Bitte umsetzen.

**Comment by BigSnicker** [comment]
Thank you!  Just found your work and it will be very helpful.

**Comment by carlobeltrame** [comment]
decidim 0.23.1 ist jetzt auf der Testumgebung ausgerollt und bereit zum Testen.

**Comment by innosmith** [comment]
Wir haben keine neuen Fehler entdeckt. @carlobeltrame bitte auf PROD deployen.
