### ISSUE TITLE
Mind. 15 Buchstaben wegkriegen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#270]
Damit das Update der Core & Awesome Version an Dringlichkeit verliert, brauche ich bis am 22.05. zwingend einen übergangsmässigen Quickfix für dass die Eingabefelder der "Reporting Proposals"-Komponente Titel und Kurzbeschrieb nicht mind. 15 Buchstaben enthalten müssen und keine Pflichtfelder sind. (Bereits in Mail vom 20.04. erwähnt).

![image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/94c53e82-8c0b-417c-b37e-34c96955a431)

**Comment by larsUE** [comment]
Winterthur wäre an diesem Fix auch fürs allgemeine Vorschlagsmodul interessiert.

**Comment by carlobeltrame** [comment]
Wir können versuchen, die [Änderungen von Decidim Awesome](https://github.com/decidim-ice/decidim-module-decidim_awesome/pull/191/files) für den Moment zu uns zu übernehmen. Wenn wir das für alle Tenants und gleichermassen für Vorschläge und Schadensmeldungen umsetzen dürfen, vereinfacht das die Sache.

**Comment by larsUE** [comment]
Von Seiten Cokreation und gemeinsamer.space wäre das super. @innosmith ich nehme an, von Seiten deinklima und köniz gibts auch keine Vetos? 

Bezüglich Update besprechen wir dann ja nächsten Dienstag mehr :) Ich könnte mir auch vorstellen, direkt auf Version 27 zu wechseln, statt auf 26.4

**Comment by carlobeltrame** [comment]
Ein Update wäre natürlich die beste Option, aber dann sind wir nicht zu 100% sicher dass bis am 22.5. alles wirklich rund läuft. Darum gibt es eben dieses Issue hier.

**Comment by Naadjjaa** [comment]
@carlobeltrame Das wäre super! 
Es ist ein Detail aber scheint uns für die Einführung des Schadenmelders sehr relevant. Wir haben schon durch die nötige Registrierung eine relativ grosse Hürde und möchten nicht, dass Meldungen nicht abgeschickt werden, weil Fehlermeldungen aufgrund von zu wenigen Ziffern die Leute vom Posten abhalten.
@innosmith Danke für eine zeitnahe Rückmeldung ob wir das so machen dürfen.

**Comment by Naadjjaa** [comment]
@carlobeltrame Wir haben grünes Licht für den Quickfix für alle decidim.swiss Tenants. Danke fürs zeitnahe umsetzen.

**Comment by carlobeltrame** [comment]
Ich habe das umgesetzt und auf Integration ausgerollt. Zur Info: Ich habe es gleich wie Decidim Awesome umgesetzt, und somit gilt der Fix nur im Proposal Create Wizard im Frontend. Wenn man Vorschläge direkt im Admin-Backend erstellt, werden die Regeln wie bisher durchgesetzt.

@Naadjjaa @innosmith @larsUE bitte seid euch bewusst dass es eine schlechte Idee sein kann, Vorschläge ohne Titel und ohne Textkörper zuzulassen. Auf Tenants die die Vorschlags-Kacheln angepasst haben und den "Vorschlag anzeigen" Button versteckt haben, ist es schwierig, einen titellosen Vorschlag zu öffnen.
![Screenshot 2023-05-15 at 16-59-37 Vorschläge - Echogruppe Dialog Luzern - Dialog Luzern](https://github.com/stadtluzern/decidim-ocl/assets/7566995/39c2d48b-25dc-4491-9d3d-ab574b762ffb)
Bei "letzte Aktivität" gibt es ebenfalls keinen Link zum Vorschlag, wenn kein Titel vorhanden ist.
![Screenshot 2023-05-15 at 17-04-43 Dialog Luzern](https://github.com/stadtluzern/decidim-ocl/assets/7566995/8a7917e6-2d62-487c-9995-7d89e990fd56)
Ich bin gespannt von euren Erfahrungen mit der Qualität der Vorschläge / Ideen / Meldungen zu hören, jetzt wo diese Qualitäts-Safeguards ausgeschaltet sind.

**Comment by Naadjjaa** [comment]
@carlobeltrame Danke für deinen Hinweis! Sobald wir die aktuellste Version von Awesome haben müssten wir diesen Quickfix wieder entfernen. Dann wird die Anzahl Buchstaben konfigurierbar sein - wir werden diese dann beim Titel wieder auf 3 Zeichen setzen.

**Comment by Naadjjaa** [comment]
@carlobeltrame Funktioniert bei meinem Test auf INT nicht:
![image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/7ae2b263-47b6-43db-9476-f29f9ffbadba)

**Comment by carlobeltrame** [comment]
@Naadjjaa hier funktionierts aber: https://test.dialogluzern.ch/assemblies/reussbuehl/f/57/proposals/new

Kannst du mir den genauen Link schicken wo du getestet hast? Oder hast vielleicht versehentlich auf PROD getestet?

**Comment by Naadjjaa** [comment]
@carlobeltrame Kann es sein, dass du das nur für Proposals angepasst hast, aber nicht für Reporting Proposals?
Hier funktionierts noch nicht:
https://test.dialogluzern.ch/processes/nadjaprozess/f/764/proposals/new

**Comment by carlobeltrame** [comment]
Danke für den Link. Das wird es wohl sein. Ich habe es genau so umgesetzt wie es in Decidim Awesome auch gemacht wurde, heisst es hätte also mit Decidim Awesome auch nicht funktioniert.

Die Reporting Proposals basieren stark auf den normalen Proposals, und ich habe auf den ersten Blick nicht gesehen, wo Pokecode dieses Formular für die Reporting Proposals separat abgeändert hat (sie haben da ausnahmsweise aus mir noch unbekannten Gründen nicht den direktesten Weg gewählt).

Somit muss ich diesen Fix noch einmal neu für die Reporting Proposals implementieren, durchtesten und auf INT ausrollen.

**Comment by Naadjjaa** [comment]
@carlobeltrame Für die Reporting Proposals kann man neu die Anzahl Buchstaben direkt im Awesome Modul konfigurieren. Es hat auf unserer Entwicklungsumgebung funktioniert. Lass uns um 9 kurz besprechen, wie dringend Matthias dieses Feature sieht.

**Comment by Naadjjaa** [comment]
![image](https://github.com/stadtluzern/decidim-ocl/assets/75797851/1607bdf1-7aab-4201-9254-3b36eba33f56)

**Comment by carlobeltrame** [comment]
Interessant. Bist du sicher dass das auch für reporting proposals funktioniert, nicht nur für proposals? Ich sehe weder im Code von Decidim Awesome Referenzen zu Reporting Proposals, noch umgekehrt. Vielleicht habe ich aber bei Decidim Awesome etwas übersehen und sie machen es cleverer als ich auf die Schnelle erkennen konnte.

Klar, das GUI habe ich nicht von Decidim Awesome übernommen. Aber die Logik dahinter, die die eigentliche Einschränkung auf 15 Zeichen abändert, habe ich 1:1 übernommen so wie ich es in Decidim Awesome sehe.

**Comment by bsantschi** [comment]
Voraussichtlich mit Decidim v0.27 gelöst, daher on hold.

**Comment by Naadjjaa** [comment]
Mit Fix auf Awesome nun gelösst.
