### ISSUE TITLE
Bug: Dummy Bild bei Blogeinträgen wird nicht mehr geladen (für den Fall, dass keines hochgeladen wird).

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#276]
<img width="546" alt="Dummy Bilder werden nicht geladen" src="https://github.com/stadtluzern/decidim-ocl/assets/75797851/04e15796-d22e-4f44-abe5-aa8c71703ad3">

**Comment by Kagemaru** [comment]
Ich habe im Moment manuell ein Default Bild auf PROD eingesetzt. Gleichzeitig release ich gerade auf INT.

Bitte teilt mir noch mit, ob dieses Bild das richtige ist.
