### ISSUE TITLE
Bug: Veranstaltungen werden mit ältester zuerst angezeigt

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#277]
Seit dem Einbau des Schadenmelders wird auf der Seite /meetings nicht mehr die zeitlich naheliegenste sondern am weitesten entfernliegenste Veranstaltung zuerst angezeigt.

**Comment by Kagemaru** [comment]
@Naadjjaa
Am besten setzen wir uns hierfür zusammen und schauen die verfügbaren Optionen an.
Hast du jetzt oder morgen Zeit für mich?

**Comment by Naadjjaa** [comment]
@Kagemaru Heute bin ich erreichbar: Jetzt bis 10.30 Uhr oder 11-12 Uhr. Nachmittags nach Absprache.
Telefonnummer siehe: https://www.stadtluzern.ch/politikverwaltung/stadtverwaltung/personenverzeichnis/206036

**Comment by Kagemaru** [comment]
Getrackt & gefixt im Rahmen von #275
