### ISSUE TITLE
Profilbilder

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#28]
Wenn ich ein Profilbild hochladen möchte, 330KB erhalte ich die Meldung, es sei zu gross. 5MG sind eigentlich erlaubt.
![Bild zu gross Profil](https://user-images.githubusercontent.com/75797851/105146620-7d955b80-5b00-11eb-96af-967382ca6c7e.PNG)

**Comment by Kagemaru** [comment]
Anscheinend ist dies nicht das Problem.
Wenn man eine zu grosse Datei hochlädt, erscheint folgender Fehler:

![Selection_013](https://user-images.githubusercontent.com/12155/105877005-c9b03680-5fff-11eb-9d8a-8664a7d38e0c.png)

Diese Fehlermeldung ist sehr schlecht gewählt. Aber anscheinend tritt dies auf, wenn das Bild höher als breit ist.

Geht:
![8k-image](https://user-images.githubusercontent.com/12155/105877199-febc8900-5fff-11eb-9700-be1ea14f0d50.jpg)

Geht nicht:
![4k-portrait](https://user-images.githubusercontent.com/12155/105877208-02501000-6000-11eb-97ba-621f6604cba5.jpg)

**Comment by Naadjjaa** [comment]
Kann man das ändern? Profilbilder sind ja leider oft hochkant..

**Comment by Kagemaru** [comment]
Ich habe mir den Source Code dazu noch angeschaut. Hochkant ist nicht das Problem, sondern ein hardcoded Maximum Limit von 3840px.

- 3840x3840: geht
- 3841x3840: geht nicht
- 3840x3841: geht nicht
- 3841x3841: geht nicht

**Comment by carlobeltrame** [comment]
Also sollten wir wohl einfach die "Anleitung für Datei" anpassen, sodass auch noch steht "maximal 3840x3840 Pixel", sowie die Validierungs-Nachricht statt "Das Bild ist zu gross" vielleicht eher "Das Bild hat eine zu hohe Auflösung" oder "Das Bild ist zu hoch oder zu breit"

**Comment by Naadjjaa** [comment]
Ich würde die folgende Fehlermeldung anzeigen: "Das Bild ist zu hoch oder zu breit (maximal 3840 x 3840 Pixel).

**Comment by carlobeltrame** [comment]
Übersetzungsschlüssel für im Term Customizer:
"Das Bild ist zu groß" -> `carrierwave.errors.image_too_big`
"Maximale Dateigröße: `%{megabytes}`MB" -> `decidim.forms.file_validation.max_file_size` (achtung, der Platzhalter `%{megabytes}` muss exakt so geschreiben im Text bleiben, keine Abstände)

**Comment by bsantschi** [comment]
(Da das Ticket zur Zeit niemandem zugewiesen ist, frage ich) @Naadjjaa wirst du die Übersetzung im Term Customizer machen können?

**Comment by Naadjjaa** [comment]
Hat funktioniert.
