### ISSUE TITLE
Fehlerseiten auf dialogluzern fehlen

### ISSUE THREAD

**Issue by carlobeltrame** [stadtluzern/decidim-ocl#281]
Wenn man auf Decidim in einen Fehler läuft (z.B. eine nicht-existente URL aufruft), dann wird seit einem Jahr auf die statischen Seiten /pages/help404 etc. weitergeleitet. @innosmith hatte diese Seiten gemäss einem [Kommentar](https://github.com/decidim-swiss/decidim.swiss/issues/7#issuecomment-1224117560) mal auf dialogluzern eingerichtet. Aktuell fehlen sie aber, und bei einem 404 kommt man in eine Endlosschleife in der man immer wieder auf /pages/help404 weitergeleitet wird.

Bitte diese Seiten wieder einrichten.

**Comment by Naadjjaa** [comment]
@carlobeltrame Wir können uns nicht erklären, weshalb die Seiten verschwunden sind. Auch im Admin Protokoll lässt sich nichts finden. Habe sie gemäss Vorbild Winterthur wieder erstellt.
