### ISSUE TITLE
Scope Type Löschen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#29]
Wenn ich den Scope-Type Wirkungsbereich löschen möchte, kommt eine Server-Fehlermeldung. Neue hinzufügen und wieder löschen geht, aber den Wirkungsbereich löschen geht nicht.

**Comment by Kagemaru** [comment]
Hmm... Ja, dies passiert weil es noch Prozesse gibt, die auf diesen Wirkungsbereich verweisen.
Dass dies einen Fehler wirft ist allerdings sehr unschön. Ich schaue mir die Validations bei Gelegenheit an.

Dazugehöriger Log Ausschnitt:
```
F, [2021-01-26T17:28:09.076071 #1] FATAL -- : [9526f5b5-4c21-458c-9dfe-19490c4d915c] ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "decidim_scope_types" violates foreign key constraint "fk_rails_4c7666b645" on table "decidim_participatory_processes" --
```
