### ISSUE TITLE
Zugehörige Part.-Prozesse wieder weglöschen in Gremien.

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#30]
Wenn man in einem Gremium einen dazugehörigen Prozess anwählt, kann man das nachher nicht mehr rückgängig machen. D.h. einen anderen anwählen geht - keinen jedoch nicht. Das wäre sehr wichtig, da eine fälschliche Auswahl schnell passiert.
![ähnliche beteilugungsprozesse](https://user-images.githubusercontent.com/75797851/105147477-88042500-5b01-11eb-9a59-3851bca6f9be.PNG)

**Comment by Kagemaru** [comment]
Dies ist ein Multi Select HTML Element, du kannst Elemente mit CTRL+Klick wieder abwählen.

Hier gibt es ein detailiertes Beispiel: https://www.w3schools.com/code/tryit.asp?filename=GN2K3DH3NC0P

**Comment by Naadjjaa** [comment]
Könnten wir im Backend einen entsprechenden Hinweis einbauen?

**Comment by Naadjjaa** [comment]
Habe mit dem Term Customizer einen entsprechenden Hinweis im Backend platziert.
