### ISSUE TITLE
Bloginhalte in Detailansicht verschoben

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#31]
Im Assembly des QV Würzenbach ist in der Blog-Komponente der Text in der Detailansicht nach links verschoben. In anderen Assemblies hingegen tritt dieser Fehler nicht auf. Siehe Bild
![Blogmodul Text](https://user-images.githubusercontent.com/75797851/105147418-73c02800-5b01-11eb-8b51-63cb78ed4fa0.PNG)

**Comment by carlobeltrame** [comment]
Das Problem wurde in https://github.com/decidim/decidim/pull/6942 bereits behoben, aber noch nicht released. Wir können den Fix provisorisch einbauen, müssen ihn aber wieder entfernen wenn wir auf eine Version > 0.23.1 updaten.

**Comment by Naadjjaa** [comment]
Wann denkt ihr wird das passieren? Spätestens Ende Februar müsste es sicher funktionieren.

**Comment by carlobeltrame** [comment]
Ich bin erst nächste Woche wieder an decidim, kann es dann machen falls Thomas es noch nicht gemacht hat bis dann. Alternativ könnt ihr "Bestätigungen" für Blog Posts aktivieren, dann tritt der Fehler nicht auf. Siehe entsprechendes Issue bei der Quartieridee: https://github.com/puzzle/quartieridee/issues/82

**Comment by Naadjjaa** [comment]
Wird sich aufgrund des Updates erledigen, oder ist 23.1 ein anderes Update als 23?

**Comment by carlobeltrame** [comment]
Das wird sich leider noch nicht erledigen. Wir updaten zwar direkt auf 0.23.1, aber der Fix ist darin noch nicht enthalten, erst in der nächsten Version die decidim rausgeben wird.
Also solange es keine Option für euch ist "Bestätigungen" zu aktivieren wie es auf der Quartieridee gemacht wurde, müssen wir den Fix für den Moment selber ausführen.

**Comment by Naadjjaa** [comment]
Ich verstehe noch nicht genau, was es heisst "Bestätigungen zu aktivieren". Handelt es sich um eine der drei untenstehenden Einstellungen in der Blogkonfiguration?
![Bestätigung aktiviert](https://user-images.githubusercontent.com/75797851/108469417-7640a980-7288-11eb-99b4-637dc115d3e9.PNG)
