### ISSUE TITLE
Nutzungsbedingungen akzeptieren besser sichtbar machen im Backend

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#33]
Wenn man einen neuen Account erstellt hat, wird der User vom System als erstes aufgefordert, die Nutzungsbedingungen zu akzeptieren. Dieser Hinweis kann einfach übersehen werden und führt dann zu Supportanfragen.

Das Bild unten zeigt die Problematik. Der User sieht grün, "alles gut" und will loslegen. Wenn der letzte Schritt (gelb hinterlegt mit der Aufforderung einen Link zu klicken und dann auf dem Folgescreen zu akzeptieren) prominenter sichtbar wäre, z.B. das Hinweisfenster rot umrandet - oder eine andere Idee - wäre es besser sichtbar.

**Comment by innosmith** [comment]
<img width="1497" alt="Anmeldung Review Bedingungen" src="https://user-images.githubusercontent.com/75796635/105196609-19908880-5b3c-11eb-851c-c035a2ea50e8.png">

**Comment by Kagemaru** [comment]
Dies mit CSS zu lösen wäre das einfachste. Wäre das ok so?
![Red Warning](https://user-images.githubusercontent.com/12155/105865176-f14cd200-5ff2-11eb-9071-a155e9cdf5c0.png)

**Comment by innosmith** [comment]
Denke das passt, bitte so umsetzen.

**Comment by Naadjjaa** [comment]
Ich habe es gerade getestet, bei mir ist es noch immer gelb.

**Comment by innosmith** [comment]
Siehe Kommentar von @Naadjjaa, scheint die Änderung noch nicht umgesetzt zu sein. Bitte prüfen.

**Comment by carlobeltrame** [comment]
Wir haben jetzt so einige Dinge versucht, und nichts scheint zu greifen. In der Dokumentation wird sogar an mehreren Stellen erwähnt, dass abgeändertes CSS im Admin-Bereich nicht greift, zum Beispiel [hier](https://docs.decidim.org/en/customize/styles/#_custom_html_header_snippets). Ein existierendes Modul welches das ermöglicht ist mir ebenfalls nicht bekannt. Auch decidim awesome kann nur das Erscheinungsbild ausserhalb des Admin-Dashboards anpassen.

Ich sehe inzwischen keine einfachere Lösung mehr als ein eigenes Modul zu schreiben. Da die benötigte Änderung eigentlich nur sehr klein ist, möchte ich hier nochmals euer Go oder NoGo abholen.

**Comment by innosmith** [comment]
Wie gross schätzt Du @carlobeltrame den Aufwand zur Erstellung eines solchen Modules?

**Comment by innosmith** [comment]
In dem Falle schliessen wir diesen Task. Nur hierfür lohnt sich der Aufwand für ein eigenes Modul nicht.
