### ISSUE TITLE
Konfiguration PROD

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#36]
Wir möchten gerne auf der PROD Umgebung langsam mit dem Erstellen des "echten" Inhalts beginnen. Dazu brauchen wir bitte die Prozesse & Assemblies. Den Kalender könnt ihr hingegen wieder wegmachen. Vielen Dank!

**Comment by Kagemaru** [comment]
Hallo Nadja,
Sowohl Prozesse als Assemblies sind schon drin. Sobald ihr sie anfangt im Admin-Backend zu befüllen erscheinen Sie auch auf der Seite.

Der Kalender ist eigentlich fest eingebaut und es gibt keinen Konfigurationsweg diesen auszublenden. Wenn ihr wollt, kann ich aber im Code den Tab rausnehmen.

**Comment by Naadjjaa** [comment]
Könnt ihr bitte den Term Customizer und Decidim Awesome auch noch auf PROD hinzufügen?

**Comment by Kagemaru** [comment]
Dann deploye ich den jetzigen INT Stand auf PROD.
Somit könnt ihr alle Tickets als "Done" markieren, die momentant als "Testable on INT" sind?

**Comment by Naadjjaa** [comment]
Wir werden nicht alles davon brauchen. Zum Beispiel soll das Kalendermodul nicht ersichtlich sein.  (Initiativen und Konferenzen ebenfalls nicht, diese zeigt es aber auch nicht an, solange wir nichts erfassen).

**Comment by Kagemaru** [comment]
Genau, somit ist dieses Ticket auch Testable on Integration.
Sobald alles auf INT getestet ist und ein ok von euch bekommt, kann ich das deployment auf PROD vornehmen.
Sind bereits alle Tickets auf "Testable on INT" für euch OK?

**Comment by Naadjjaa** [comment]
Wir haben alles geprüft. Gerne auf PROD deployen. Und bitte wie erwähnt das Kalender Modul auf beiden Plattformen deaktivieren.

**Comment by Naadjjaa** [comment]
Es wäre wichtig, dass dies bald gemacht wird. Wir haben seit gestern Vereine auf PROD und z.B. die Eventerstellung funktioniert nicht, da dies erst auf INT angepasst wurde. Danke

**Comment by Kagemaru** [comment]
Ich habe nun alles auf PROD deployed. Das Ticket kann nach Done verschoben werden sobald ihr damit auf PROD zufrieden seid.
