### ISSUE TITLE
OCL UX Review

### ISSUE THREAD

**Issue by juebaum** [stadtluzern/decidim-ocl#39]
Vorschläge erarbeiten zur Optimierung von:
1. Startseite
2. Filterkonzept
3. Letzte Aktivität (Startseite)
4. Vereinsseite

**Comment by bsantschi** [comment]
Hoi @Naadjjaa, ich glaube das hatte kurz vor deiner Präsentation keine Prio mehr. Bitte auf Jürgen zugehen, wenn er was machen darf. Bis dahin schiebe ich es zurück ins Backlog.
