### ISSUE TITLE
Bildgrösse

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#41]
In Assemblies: Könnt ihr im Code sehen auf welche Grösse die Bilder für die Kachel bzw. den Banner zugeschnitten werden?

**Comment by Naadjjaa** [comment]
![Bild Banner](https://user-images.githubusercontent.com/75797851/106468547-5ba3bd80-649e-11eb-8dcc-206cfa008fba.PNG)
![Bild Kachel](https://user-images.githubusercontent.com/75797851/106468552-5d6d8100-649e-11eb-8639-f69d6cbc96c4.PNG)

**Comment by Kagemaru** [comment]
Im Code sehe ich, dass das Hauptbild auf 1000x1000 reduziert wird. Das Banner Bild hingegen wird gar nicht verkleinert.

**Comment by carlobeltrame** [comment]
Wenn es genügend Platz hat werden die Bilder mit der Grösse 418x160px angezeigt, das ist ein Seitenverhältnis von ungefähr 10:4. Aber wenn der Bildschirm kleiner ist (z.B. auf Tablet oder Mobile) kann das auch etwas abweichen, und es ist auch nicht garantiert dass sich das mit zukünftigen decidim-Updates nicht ändert. Ich würde die Bilder einfach mindestens in dieser Auflösung hochladen. Gerade beim Gremium / Organisation wird glaube ich dasselbe Bild dann ja auch noch als grosses Banner auf der Detailansicht angezeigt.

**Comment by Naadjjaa** [comment]
Das Bannerbild wird separat hochgeladen. Könnt ihr da auch noch das Format auslesen? Danke

**Comment by carlobeltrame** [comment]
Beim Bannerbild variiert die Anzeige noch sehr viel mehr als beim Vorschaubild auf den "Kärtli", es gibt kein fixes Seitenverhältnis:


https://user-images.githubusercontent.com/7566995/107338539-f3676400-6abb-11eb-951e-933c68ea70cb.mp4


Das Bannerbild nimmt die Breite des Bildschirms an, höchstens jedoch 1920px. Die Höhe beträgt aktuell immer 124.8px, unabhängig davon wie gross das Bild aufgeblasen ist. Die Höhe können wir mit #45 auch selber wählen, aber damit es so aussieht wie dort spezifiziert müssen wir uns wieder auf eine fixe Höhe einigen.
Wir können zudem für die ganze Plattform (decidim-weit) festlegen, ob bei allen Banner-Bildern der obere Rand, die Bildmitte oder der untere Rand immer sichtbar bleibt (also ob nur von unten, nur von oben, oder von beiden Richtungen gleich viel abgeschnitten wird).

**Comment by Naadjjaa** [comment]
Ich würde vorschlagen, dass wir für #45 eine Höhe von 150px festlegen. Sichtbar würde ich die Bildmitte lassen. Ich werde die Formate entsprechend so gegenüber unseren Pilotvereinen kommunizieren.
