### ISSUE TITLE
Dauer eines Assemblies

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#42]
In den Assemblies gibt es eine Sektion zum Thema "Dauer". Wenn man kein Enddatum angibt steht im Frontend dann Dauer unbestimmt. Kann man dieses Feld ausblenden, solange nichts reingeschrieben ist?

**Comment by Naadjjaa** [comment]
![Metadaten Assembly](https://user-images.githubusercontent.com/75797851/106470701-1a60dd00-64a1-11eb-8599-e5e3eeeca1e1.PNG)

**Comment by Kagemaru** [comment]
Dafür müsste man das ganze Template patchen, was zwar möglich ist. Später aber sehr nervig, weil man daran denken muss allfällige Änderungen von Updates am Ursprungstemplate zu übertragen. Andererseits wäre das eventuell eine Möglichkeit eine über den Term Customizer angepasste URL in diese Sidebar zu bekommen. Somit wäre dies eine Möglichkeit #22 zu lösen.

**Comment by carlobeltrame** [comment]
Wenn ihr die Dauer sowieso für kein Assembly setzt wäre es wohl am einfachsten, wenn wir den Eintrag ganz ausblenden. Das wäre sehr leicht mit CSS zu machen. Wenn ihr es aber anzeigen wollt je nach dem ob es vorhanden ist, müsste man es so machen wie Thomas kommentiert hat.

**Comment by Naadjjaa** [comment]
Ganz ausblenden ist gut, danke!

**Comment by carlobeltrame** [comment]
Ist erledigt in fde784f38b1454fab88eae6b9de374a38282aedc und auf der Integration verfügbar.
