### ISSUE TITLE
Vorschlagstextänderungen können nicht fehlerfrei erfasst werden

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#43]
Wenn man Vorschlagstextänderungen erstellen und speichern will, kommt am Ende jeweils folgende Fehlermeldung:

"Auf unserem Server ist ein Problem aufgetreten".

Bitte rasch fixen.

**Comment by carlobeltrame** [comment]
Ich habe das auf Integration behoben, es was dasselbe Problem wie wir schon in puzzle/quartieridee#49 und puzzle/decidim-zuerich#17 bemerkt hatten.
