### ISSUE TITLE
UX - Organisationsseite (Vereinsseite) umgestalten

### ISSUE THREAD

**Issue by juebaum** [stadtluzern/decidim-ocl#45]
Ausgangslage: Lesbarkeit von Titeln im Banner ist nicht optimal. Layout wirkt insgesamt sehr gedrängt.  

Ziel: 
- Banner Bild blauer Bereich weglassen 
- Mehr vom Bannerbild zeigen (Höhe)
- Vereinsname, Hashtag, Slogan unter Banner darstellen (mehr Whitescreen) 
- Tab Labels nicht UPPERCASE (wirkt autoritär), analog Hauptnavigation

Prüfen Umsetzbarkeit:
- Vereinslogo-Upload (ähnlich wie auf anderen Plattformen), viereckiger Bereich für Logo. Funktionsweise: Falls kein Bild hochgeladen, soll nichts dargestellt werden. Hinweis: die Bilder (Bannerbild, Homeimage) können nicht verwendet werden. Homeimage wird für die Karten auf der Organisationsübersicht gebraucht.   
- Positionierung Bannerbild. Problem, dass je nach Bild Köpfe abgeschnitten sind. Prüfen, ob hier eine Lösung zur Positionierung möglich ist.

**Comment by juebaum** [comment]
![organisationsseite](https://user-images.githubusercontent.com/78081549/106724797-f4eee300-6608-11eb-86b0-1f3fe8d8511c.png)

**Comment by carlobeltrame** [comment]
Ist implementiert und auf der Testumgebung ausgerollt. Für Organisations-Logos habe ich auf die Schnelle keine einfache Lösung gefunden. Der Rest ist in etwa so wie auf dem Mockup von Julian umgesetzt: https://ocl-test.puzzle.ch/assemblies/reussbuehl

**Comment by Naadjjaa** [comment]
Bitte auf PROD übertagen.

**Comment by carlobeltrame** [comment]
Okay, noch heute? Oder lieber nach der Präsentation?

**Comment by Naadjjaa** [comment]
Gerne noch heute.
