### ISSUE TITLE
UX - Design Email-Notification

### ISSUE THREAD

**Issue by juebaum** [stadtluzern/decidim-ocl#46]
Ausgangslage: Mail wirkt dunkel und entspricht nicht der Webpage hinsichtlich Design. 

Ziel: 
- Header freundlicher/heller gestalten, Footer hat redundante Infos, allenfalls mit sinnvollen Infos ergänzen. 
- Farbengebrauch wie auf Webpage
- Logo einfügen (wenn dann vorhanden)

**Comment by Naadjjaa** [comment]
In Zusammenarbeit mit Stadthirsch. Auf definitiven Layoutentscheid warten.
