### ISSUE TITLE
UX - Organigramm auf Ebene Organisationen ausblenden

### ISSUE THREAD

**Issue by juebaum** [stadtluzern/decidim-ocl#47]
Ausgangslage: Organigramm bietet keinen Mehrwert und hat eine sehr nervöse Bedienung.

Ziel: Ausblenden, wenn Nadja damit einverstanden ist.

**Comment by juebaum** [comment]
![organigramm](https://user-images.githubusercontent.com/78081549/106727231-88c1ae80-660b-11eb-9214-b268dd24fd81.png)

**Comment by Naadjjaa** [comment]
Dass können wir selbst übernehmen, ist eine Option im Backend.

**Comment by Naadjjaa** [comment]
Unter Assemblies - Einstellungen kann dies abgestellt werden.
