### ISSUE TITLE
UX - Bug Filter, laden der Seite in modalem Fenster

### ISSUE THREAD

**Issue by juebaum** [stadtluzern/decidim-ocl#48]
Ausgangslage: Wenn auf der Ebene Organisationen (Abschnitt Gremien) im Filter Bereiche (links) der Filter geöffnet wird (modales Fenster) und die Auswahl storniert wird, lädt es im modalen Fenster den Inhalt der Organisationsseite, anstatt dass das modale Fenster geschlossen wird. 

Ziel: fixen.

**Comment by juebaum** [comment]
![bug_01](https://user-images.githubusercontent.com/78081549/106726583-d689e700-660a-11eb-9608-56f8314b6b5d.png)
![bug_02](https://user-images.githubusercontent.com/78081549/106726599-dab60480-660a-11eb-9cfa-dea48739f07b.png)

**Comment by innosmith** [comment]
Dasselbe passiert auch im Backend, wenn man z.B. einer Organisation einen Scope Type zuweisen möchte aber anstelle auf "stornieren" klickt.

**Comment by carlobeltrame** [comment]
Bug ist bei decidim bekannt (https://github.com/decidim/decidim/issues/7621) und wird in 0.25 behoben. Ich habe den Fix vorgeholt und auf Integration deployed.

**Comment by innosmith** [comment]
Funktioniert jetzt, danke.
