### ISSUE TITLE
UX - Suchfeld als Suchfeld darstellen

### ISSUE THREAD

**Issue by juebaum** [stadtluzern/decidim-ocl#49]
Ausgangslage: Das Suchfeld in der Metanavigation ist schwierig zu erkennen, da der Rahmen fehlt (wenig Aufforderungscharakter).

Ziel: Rahmen wieder anzeigen.

**Comment by juebaum** [comment]
![suchfeld](https://user-images.githubusercontent.com/78081549/106727082-6596ff00-660b-11eb-811b-59b009ba96d7.png)

**Comment by Naadjjaa** [comment]
Passt, danke!
