### ISSUE TITLE
WAF Aufbau

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#52]

**Comment by Kagemaru** [comment]
Eine erste Version der WAF ist jetzt auf der OCL INT im Einsatz.
Aufgrund Technischer Unterschiede zu HitoBito fahren wir im Moment mit folgendem Ablauf:
1. NGINX Webserver (HTTP Basic Auth / SSL Termination)
2. Apache Webserver (WAF)
3. NGINX Webserver (Asset delivery)
4. Rails Webserver (App)

Dies hat noch Optimierungspotential, da auch die WAF das Basic Auth übernehmen könnte.
Entsprechende Konfigurationsmöglichkeiten möchte ich noch mit @franbuehler anschauen.

Des weiteren ist ein Teil der Kommunikation innerhalb von Openshift noch unverschlüsselt. Da dies auch zwischen zwei verschiedenen Nodes geschehen kann, wird so unverschlüsselt über ein Netzwerk kommuniziert. Laut Severin Räz ist hierbei eine OpenShift seitige Lösung bei Puzzle im Gespräch. Falls dies dringend ist, muss man eine Lösung prüfen, die in jedem Container SSL Termination / Reencrypt implementiert. Aus Zeitgründen wurde dies bei der ersten Implementation ausgeklammert.

Sollen wir den Technical Debt der daraus resultiert in einem separaten Ticket tracken?

**Comment by franbuehler** [comment]
Logging nach JSON Format ändern? Wäre das ein Wunsch?

**Comment by franbuehler** [comment]
Passwörter dürfen nicht geloggt werden.

**Comment by franbuehler** [comment]
- WAF läuft und funktioniert soweit.
- Merge des Tuning MR ausstehend. Das müssen wir nächste Woche zusammen ansehen -> Thomas und ich.
- Basic Auth habe ich noch nicht geschafft... Ich weiss nicht, ob ich das schaffe. Könnte man im Notfall mit NGINX produktiv gehen? -> Antwort: JA
- Läuft die Umgebung schon auf Prod -> Antwort: JA

Meine Empfehlung: Ich würde übrigens trotz Tuning nicht mit der scharfen WAF produktiv gehen, sondern noch mit erhöhten Limiten.

**Comment by Kagemaru** [comment]
Beide Tuning MRs wurden auf INT deployed und funktionieren.
PROD Deployment machen wir später.
