### ISSUE TITLE
Komponente Sortierung löschen führt zu Fehler

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#59]
Siehe Screenshot führt das Löschen einer zuvor erstellten Komponente "Sortierung" zu einem Fehler, wenn der User auf der Komponentenübersicht auf das rote X zum Löschen klickt.

**Comment by innosmith** [comment]
![Screenshot 2021-02-10 at 10 12 44](https://user-images.githubusercontent.com/75796635/107497076-5e836a00-6b92-11eb-93f6-a0cd7719756b.png)

**Comment by Kagemaru** [comment]
Dies scheint ein Problem mit Sortitions als solches zu sein. Es ist gewollt, dass man die Komponente nicht löschen kann, solange es noch Einträge enthält. Aber die Inhalte können nirgends gelöscht werden.
Ich werde es vorerst mal in der Konsole entfernen.
