### ISSUE TITLE
Schriften anpassen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#65]
Ich werde euch morgen, Donnerstag, 18.02. Bescheid für die Schriften geben. Dies hat dann für die Umsetzung Priorität. Dies als Vorinformation.

**Comment by Naadjjaa** [comment]
Bitte folgende Schrift einbauen. https://fonts.google.com/specimen/Source+Sans+Pro?preview.text_type=custom#standard-styles

Könnt ihr die H1-H6 bitte zudem wie im Bild konfigurieren?

Könnt ihr im Texteditor (für Content aus den Vereinen) die Schriften H1-H4 nicht mehr auswählbar machen?

**Comment by Naadjjaa** [comment]
![H1-H6](https://user-images.githubusercontent.com/75797851/108335859-af6b1200-71d3-11eb-8865-c5d3383667f8.PNG)

**Comment by Naadjjaa** [comment]
Siehe auch diese PDF
[210218_E_Flyer_V2.pdf](https://github.com/stadtluzern/decidim-ocl/files/6001697/210218_E_Flyer_V2.pdf)

**Comment by carlobeltrame** [comment]
Die Schriftart Source Sans Pro ist übrigens sogar schon der Standard für decidim, wird aber normalerweise nur angezeigt wenn der Benutzer die Schrift fix auf seinem Computer installiert hat. Ich habe sie jetzt noch so auf der Seite installiert dass alle Benutzer diese Schrift sehen sollten.

Die Überschriften habe ich wie im Bild konfiguriert. Leider sind im PDF die Überschriften falsch zugeordnet. Die Überschrift "Meetings" ist zum Beispiel kein H2 sondern ein H4, und die Buttons sind gar keine headings. Die Buttons und Rahmenlinien etc. die im PDF sind nehme ich aber auch nicht an dass diese in diesem Issue "Schriften anpassen" bereits umgesetzt werden sollen, oder?

Die Copy-Schriftgrösse habe ich nicht umgesetzt, da die 1.5-fache Vergrösserung die Benutzeroberfläche sehr anders aussehen lässt. Auf den Mockups im PDF ist das auch nicht so zu sehen, dort sieht die normale Textgrösse eher aus wie bisher.
