### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#66]
Auf der Startseite müssten wir die Möglichkeit haben, im Hauptbild keinen Text und keinen Button zu haben. Geht das?

Kann das Bild zentriert werden statt wie aktuell linksbündig?

Welches Format sollten wir hier idealerweise hochladen?

**Comment by carlobeltrame** [comment]
Ich kann im Hauptbild Text und Button ausblenden, dann habt ihr aber nicht die "Möglichkeit" das bei Bedarf zu ändern. Ausserdem ist das aus Accessibility- und SEO-Sicht nicht das beste, wenn der Titel der Seite nur in einem Bild vorhanden ist. Einen Alt-Text kann man leider auch nicht hinterlegen. Aber für die Präsentation wirds wohl so reichen müssen.

Bild zentrieren wird gemacht. Auf Handy-Bildschirmen sieht man dann aber nur noch den mittleren Teil des Schriftzugs.

Vom Format her gilt auch hier wieder: Das Banner passt sich in der Breite dem Bildschirm an. Soweit ich sehe ist es nie höher als 424.4px.
