### ISSUE TITLE
Im Hauptmenu Start durch Logo ersetzen?

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#67]
Ein Klick auf das Logo führt automatisch zur Startseite. Daher finden wir das Start in der Hauptnavigation überflüssig. Kann man dieses ausblenden?

**Comment by innosmith** [comment]
@Naadjjaa: ich bin mir nicht sicher, ob unsere User das Logo immer als Link für die Startseite erkennen, weil die Hauptnavigation tiefer angesetzt ist als das Logo.

**Comment by Naadjjaa** [comment]
Mich stört es auch nicht, dies war ein Input von Silvan. Ticket schliessen? @innosmith

**Comment by innosmith** [comment]
Wir lassen es beim Standard und schliessen das Ticket.
