### ISSUE TITLE
Email-Server für info@dialogluzern.ch bereit

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#68]
Wir haben bei Metanet die neuen Domains registriert und ein Email-Hosting eingerichtet.

Bitte alle Emails neu als "info@dialogluzern.ch" absenden. Details zum Mailserver siehe Screenshot.

**Comment by innosmith** [comment]
<img width="495" alt="Screenshot 2021-02-18 at 09 53 56" src="https://user-images.githubusercontent.com/75796635/108353137-11ce0d80-71e8-11eb-9c32-c1bb1fc57a65.png">

**Comment by carlobeltrame** [comment]
Hallo @innosmith
Ich habe die Angaben soweit eingetragen. Das Passwort darfst du gerne selber noch im System-Dashboard `/system` eintragen gehen. (Das "From label" kann man momentan nicht einfach so eintragen wegen einem decidim Bug, ich ergänze das noch wenn du das Passwort eingetragen hast).

Die Einstellungen werden aber erst greifen, wenn entweder Thomas https://github.com/puzzle/decidim-zuerich/issues/70 überall gefixt hat, oder wenn wir auf decidim >= 0.23.2 geupdatet haben.

**Comment by innosmith** [comment]
Passwort ist als system eingetragen und gespeichert. Bez. #70 macht wohl ein Upgrade mehr Sinn - Kosten/Nutzen? Was denkt ihr?

**Comment by carlobeltrame** [comment]
Ja wäre auch mein Vorschlag. Jetzt wo ich es mir anschaue könnte es sogar sein dass ich für eine solche 0.0.1-Änderung nur neu deployen muss. Ich verifiziere diese Hypothese auf der Integration und würde das dann gleich auch auf der Produktion übernehmen, falls für euch okay so.

**Comment by innosmith** [comment]
Ja das passt für uns, Upgrade wenn die Hypothese stimmt.

**Comment by Kagemaru** [comment]
Aufgrund des baldigen Go-Live, bevorzugen wir vorerst den Fix (war sowieso von einer anderen Instanz schon bereit). Dann haben wir keine unbekannten Instabilitäten der neuen Version.
Der Fix wurde nun auf INT deployed. Nachdem erneuten setzen der Mail Settings in /system, sollten diese greifen und bei neuen Mails angewendet werden.

**Comment by innosmith** [comment]
Ich habe im /system die Mail Settings für info@dialogluzern.ch eingestellt. D.h. wir testen jetzt den Emailversand auf INT.

**Comment by innosmith** [comment]
Von INT erhalten wir durch Decidim generierte Emails mit korrektem Header. Im Postausgang von info@dialogluzern.ch erscheint diese Email nicht, muss aber auch nicht sein.
