### ISSUE TITLE
Event nicht mehr bearbeitbar

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#71]
In der Organisation Sportstadt Luzern auf PROD gibt es einen Event, der sich nicht mehr bearbeiten lässt. Könnt ihr sehen, wieso das so ist?

**Comment by Naadjjaa** [comment]
![Event nicht bearbeiten](https://user-images.githubusercontent.com/75797851/109116003-24909700-7740-11eb-82f6-a5983bd7d21c.PNG)

**Comment by carlobeltrame** [comment]
Der Unterschied ist, dass der nicht bearbeitbare Event vom User "Sportstadt Admin" erstellt wurde, während die anderen als Autor die Organisation eingetragen haben. Letzteres macht die Events zu "offiziellen Events", und nur offizielle Events können von uns im Admin-Bereich bearbeitet werden. Ich würde annehmen dass der Account "Sportstadt Admin" als Autor den Event immer noch bearbeiten kann.

Ich weiss selber nicht genau, wie genau man die beiden Arten von Events erzeugt. Soll ich da noch weiter nachforschen oder wollt ihr in der Dokumentation suchen?

**Comment by Naadjjaa** [comment]
Merkwürdig. Die Organisation hat überhaupt erst mit einem Login Zugriff. Könnt ihr den Event notfalls auch manuell löschen?
Falls ja, gerne diesen einen Event löschen. 

Nachforschen gerne wieder, sobald alle anderen Prios fertig sind.

**Comment by carlobeltrame** [comment]
Habe noch eine bessere Lösung gefunden: Ich habe den Autor dieses Events auf den Tenant gesetzt, sodass der Event auch zum offiziellen Event ernannt wurde. Die Bearbeitungs-Funktionen sind jetzt für mich verfügbar. Bitte erneut eröffnen falls noch etwas nicht klappt.

**Comment by carlobeltrame** [comment]
Übrigens, ich glaube ich habe noch etwas mehr herausgefunden:
Offizielle Events (die man weiterhin als Admin bearbeiten kann) macht man über das Administrations-Panel, wie ihr es euch schon gewohnt seid.
"Persönliche" Events entstehen, wenn ein User im Frontend den "Neuer Event" Knopf benützt (das wurde für 0.23 neu implementiert, siehe [hier](https://github.com/decidim/decidim/issues/5726) - "Nova trobada" heisst "Neues Meeting" auf katalanisch).
In der [decidim-Dokumentation](https://docs.decidim.org/en/admin/component_meetings/) ist die Unterscheidung bereits erfasst, aber noch nicht beschrieben, wie die beiden Arten von Meetings erstellt werden, oder ob und wie man vom einen aufs andere umschalten kann.
