### ISSUE TITLE
Organisations-Übersicht

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#74]
Wenn eine Organisation ein grosses Bild für die Organisation hochlädt, wird die Übersicht etwas hässlich verzogen. Kann man hier etwas dagegen machen?

**Comment by Naadjjaa** [comment]
![Kacheln auf Organisationsübersicht](https://user-images.githubusercontent.com/75797851/109627303-c7328680-7b41-11eb-95fd-c5a3aaaf446c.PNG)

**Comment by carlobeltrame** [comment]
Das Problem ist nicht, dass das Bild zu gross ist, sondern dass das Bild in den Beschreibungstext hineingezogen wurde, statt es in den dedizierten Feldern für Haupt-Bild und/oder Banner-Bild hochzuladen. Ich würde diesem Quartierverein empfehlen, das Bild aus dem Text zu entfernen und stattdessen korrekt hochzuladen.
