### ISSUE TITLE
Warum haben wir für OCL ein anderes Repo für den TermCustomizer?

### ISSUE THREAD

**Issue by Kagemaru** [stadtluzern/decidim-ocl#77]
Ich bin dafür, die gleiche Herkunft für den TermCustomizer bei allen Projekten zu haben. Wenn dieses Repo einen Vorteil hat, können wir dies bei den anderen einbauen.

Der Nachteil vom nicht offiziellen Repo ist, dass dort mein Fix (noch?) nicht eingebaut wurde.

Was meinst du @carlobeltrame?

**Comment by carlobeltrame** [comment]
Ja ich fände es auch besser, überall dasselbe Repo zu verwenden. Das "nicht offizielle" musste ich aber beim Upgrade auf decidim 0.23.1 einbauen, da dem offiziellen Term Customizer die Einstellung dafür fehlt: https://github.com/EntraInAzione/decidim-module-term_customizer/commit/8453d7f9149582e5c95adfbcff7310859cb3dab2
