### ISSUE TITLE
Bilder in Textteilen werden nicht mehr angezeigt.

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#78]
Überall, wo im Texteditor Bilder hochgeladen wurde, sind diese nur noch als Icon zu sehen.

**Comment by Naadjjaa** [comment]
![Bilder nicht mehr angezeigt](https://user-images.githubusercontent.com/75797851/109948799-f6303000-7cda-11eb-94d0-82aba2af610a.PNG)

**Comment by carlobeltrame** [comment]
Auf den ersten Blick hängt das Problem mit der Domain-Umstellung zusammen. Die Bilder werden noch von ocl-prod.puzzle.ch her geladen, nicht von der definitiven Domain. Diese Domain ist ebenfalls noch mit Basic Authentication geschützt, was dazu führt dass die Bilder nicht geladen werden können.
Es könnte sein, dass die Bild-URLs fix in der Datenbank gespeichert werden, statt beim Seitenaufruf dynamisch zusammengestellt zu werden. Falls das der Fall ist, müssten wir einfach alle diese Bild-URLs einmalig in der Datenbank auf die neue Domain anpassen.
So oder so denke ich sollte das Problem für den User verschwinden, sobald die Basic Authentication (der Passwortschutz der Seite) entfernt wird.

**Comment by carlobeltrame** [comment]
Wir konnten es gerade kurz testen, wenn Basic Authentication ausgeschaltet ist werden die Bilder normal angezeigt. Falls noch Zeit ist vor dem Go-Live können wir noch die Datenbank durchgehen und die Links korrigieren, aber ansonsten funktionierts aus Benutzer-Sicht auch ohne.
Übrigens: Wenn man ein neues Bild in den Editor zieht sollte es weiterhin funktionieren, da dann wohl die neue Domain in die Bild-URL geschrieben werden sollte.

**Comment by bsantschi** [comment]
Nadja, funktioniert das nun wie gewünscht?

**Comment by Naadjjaa** [comment]
Ja, hatte mit der Passwortsperre zu tun.
