### ISSUE TITLE
test.dialogluzern.ch führt zur Zertifikatsfehler

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#79]
Gleich wie die www.-Domains muss wahrscheinlich auch für test.dialogluzern.ch noch ein Zertifikatsthema seitens Appuio gelöst werden.

test.dialogluzern.ch ist seitens Metanet konfiguriert und müsste dann auf den Test/INT-Server zeigen.

**Comment by Kagemaru** [comment]
Nach dem Umzug ist bei APPUiO ein Bug mit den Zertifikaten aufgetreten. Momentan haben wir das Issue für test.dialogluzern.ch umgangen und es hat ein valides Zertifikat.

Das Problem besteht noch, sollte aber in den nächsten Tagen durch VSHN behoben werden.
Damit die Lösungsfindung nicht die INT Umgebung beeinträchtigt, habe ich eine neue Dummy-Umgebung erstellt.
Diese wird wieder gelöscht, nachdem das Problem gelöst ist.

**Comment by innosmith** [comment]
@Kagemaru : kein Zertifikatsfehler mehr, aber ich kann mich mit ocltest und dem bisherigen PW nicht mehr anmelden. Hat sich was geändert?

**Comment by Kagemaru** [comment]
Ja, es gab noch ein Problem mit dem Login. Jetzt funktioniert es.
