### ISSUE TITLE
Veranstaltungen nach Datum ordnen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#80]
Ist es kompliziert, die Veranstaltungen nach Datum geordnet anzeigen zu lassen? 
Auf der Startseite ist das so, in der Detailansicht aller Events jedoch nicht.

**Comment by Naadjjaa** [comment]
Funktioniert, super!

**Comment by Naadjjaa** [comment]
Warten wir hier noch auf etwas bestimmtes, um es zu deployen?

**Comment by carlobeltrame** [comment]
Nein, wir machen nur meistens nicht ohne konkrete Aufforderung Produktivdeployments, da diese jeweils mit einer kurzen Downtime verbunden sind. Ich habe jetzt den aktuellen Stand auf der Produktion ausgerollt.
