### ISSUE TITLE
Newsletter Meldung bei Registrierung

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#81]
Das folgende Pop-Up erscheint, wenn man den Newsletter nicht aktiviert bei der Registrierung. Kann man dieses weglassen? 

Falls das nicht einfach geht, müsste wenigstens das Feld "Uncheck" umbennt werden (ist nicht als Key hinterlegt).

**Comment by Naadjjaa** [comment]
![Newsletter Uncheck](https://user-images.githubusercontent.com/75797851/110354330-5525da00-8038-11eb-81b3-c3020958a592.PNG)

**Comment by bsantschi** [comment]
"Uncheck" umbenennen in "Weiter ohne Newsletter"

**Comment by carlobeltrame** [comment]
Fun fact: Diese Übersetzung stammt ebenfalls von mir...
![Screenshot from 2021-03-10 09-00-38](https://user-images.githubusercontent.com/7566995/110596094-2bc39600-817f-11eb-847b-cf107ccce8f0.png)
