### ISSUE TITLE
E-Mail Header Bild

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#82]
Bild erscheint nicht (betrifft alle Umgebungen)

- Schritt 1 (wie Quartieridee) Bild ausbauen.
- Schritt 2 Ticket bei Decidim lösen

**Comment by innosmith** [comment]
Habe eine Email zum Download meiner Kontodaten getriggert. Kann jetzt sogar das verschlüsselte Zip lesen. 

Fazit: Die Email ohne Bilder funktioniert m.E. Der Absender ist aber nur noch dank der Email-Absenderadresse klar erkennbar. Anstelle eines Bildes sollte nun besser "Dialog Luzern" als Text erscheinen, dann wäre es noch klarer.

**Comment by larsUE** [comment]
Möglicherweise wurde das hier gelöst: decidim/decidim#7079
