### ISSUE TITLE
Anmeldehinweis

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#83]
Trotz Eintrag im Term Customizer lässt sich dies nicht anpassen:

Melden Sie sich mit Ihrem Konto an oder Melden Sie sich an, um Ihren Kommentar hinzuzufügen.

**Comment by Naadjjaa** [comment]
![Anmelden](https://user-images.githubusercontent.com/75797851/110900769-94d41680-8303-11eb-849c-2d4da5d68c05.PNG)

**Comment by carlobeltrame** [comment]
Das ist bei der Quartieridee auch schon aufgefallen. Dort habe ich die Situation so beschrieben:
> Diese Übersetzung ist technisch tiefer in decidim "eingebacken" als die anderen Übersetzungen, daher kann sie mit unserem bisherigen Approach nicht angepasst werden. Wir können den Decidim-Entwicklern einen grammatikalisch korrekten Satz in "Sie"-Form auf Crowdin vorschlagen, und könnten den dann mit dem nächsten Release von Decidim aufschalten. Später könnte man mit den Decidim-Entwicklern auch über eine technische Anpassung ihres Systems sprechen. Aber kurzfristig sehe leider ich keine gute Möglichkeit, diese Übersetzung zu ändern.

Ich habe vor drei Monaten die offizielle Übersetzung korrigiert auf "<a href="%{sign_in_url}">Melden Sie sich mit Ihrem Konto an</a> oder <a href="%{sign_up_url}">registrieren Sie sich</a>, um Ihren Kommentar hinzuzufügen.", aber das kommt leider erst mit decidim 0.24 (die ersten Beta-Versionen von 0.24 sind jetzt draussen).

Als Alternative müssten wir die TypeScript-Assets von decidim während dem Deployen neu kompilieren. Das wäre wohl ein einmaliger Aufwand von ca. 1-2 Tagen Arbeit.

**Comment by carlobeltrame** [comment]
Auch diese Situation wird sich mit decidim 0.24 [vereinfachen](https://github.com/decidim/decidim/pull/6498), die Übersetzung wird dann gleich wie alle anderen anpassbar sein. Wie Antti Hukkanen beschreibt ist es bis 0.23 ein sehr grosser Aufwand, Dinge am Kommentar-Modul zu ändern, der in keinem Verhältnis zur Grösse dieser Änderung steht. Wenn ihr das wirklich bereits jetzt haben müsst können wir den Aufwand natürlich betreiben, er wird aber nach einem nächsten Upgrade wieder obsolet werden.

Übrigens, decidim 0.24.0 wurde heute released: https://github.com/decidim/decidim/releases/tag/v0.24.0

**Comment by Kagemaru** [comment]
@innosmith Für mich wäre dies auch ein Kandidat für `Wait to Upgrade v0.24`

**Comment by innosmith** [comment]
Danke für die Abklärungen. Ein Upgrade auf v0.24 drängt sich wegen verschiedener Updates auf der INT-Umgebung auf. Ich kläre dies morgen mit @Naadjjaa.

**Comment by innosmith** [comment]
@Naadjjaa : ist das jetzt behoben dank v0.24?

**Comment by Naadjjaa** [comment]
Behoben
