### ISSUE TITLE
Link "Mehr Informationen" auf Startseite führt ins leere

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#84]
Hoi @Naadjjaa kannst du das bei Gelegenheit überprüfen und evtl. gleich selber korrigieren? Auf https://dialogluzern.ch sollte "Mehr Informationen" anstelle auf https://dialogluzern.ch/pages/faq möglicherweise auf https://dialogluzern.ch/pages/was linken.

**Comment by Naadjjaa** [comment]
Danke. In diesem Block der Startseite kann ich den Link leider nicht anpassen. Habe daher den Link in den Seiten angepasst.
