### ISSUE TITLE
Performance der Startseite

### ISSUE THREAD

**Issue by bsantschi** [stadtluzern/decidim-ocl#85]
Die Startseite lädt im Vergleich zu anderen Seiten langsam. Der Verdacht besteht, dass es mit dem Laden/Anzeigen der Veranstaltungen zu tun hat. Oder spielt uns hier die WAF einen Streich?

Startseite: > 2000s
Partizipieren: <800ms
Organisationen: <800ms
Veranstaltungen: > 1700ms
Marktplatz: <700ms
Info: <500ms

**Comment by Kagemaru** [comment]
Ich habe mal lokal getestet. Ohne WAF, development build/assets.
Wie Luzern: ~1803-2283ms
Hauptseite ohne Statistiken: -800ms
Hauptseite ohne Alles: ~1000ms

**Comment by bsantschi** [comment]
Verstehe ich deine Analyse richtig, dass
- die WAF die Performance nicht negativ beeinflusst
- der Abschnitt "Statistiken" fast die Hälfte der Ladezeit verursacht?

**Comment by Kagemaru** [comment]
Genaue Aussagen zur Performance der WAF kann ich noch nicht machen.
Dafür ist der Unterschied von lokalem DEV Environment und remote PROD Environment zu gross.
Ich meinte damit nur, dass sie lokal keinen Einfluss hat.

Ja, der Abschnitt Statistiken hat bei mir lokal den grössten Einfluss auf die Ladezeit von ~35%-45%.

**Comment by bsantschi** [comment]
@innosmith wie wichtig sind euch die Statistiken auf der Startseite? Könnten wir die allenfalls entfernen oder sollen wir uns da tiefer einarbeiten?

**Comment by franbuehler** [comment]
Wenn gewünscht, kann ich hier am Montag auch noch kurz reinschauen. Vielleicht fällt mir gerade etwas auf.

**Comment by innosmith** [comment]
Bessere Performance ist wichtiger. Wir haben die Statistiken vorerst von der Startseite entfernt. Die Veranstaltungen (eigene Seite) selbst lädt ja ebenfalls langsam. Ist ja nur wenig schneller als die Startseite. Gibt es hierzu bereits Insights?

**Comment by Kagemaru** [comment]
@innosmith Wie du in der Tabelle unten sehen kannst, liegen die hohen Rendering Zeiten in decidim-core, decidim-awesome und vor allem in decidim-meetings.

Um diese Zeiten zu optimieren, muss man eventuell mit den Einstellungen dieser Module herumspielen oder tatsächlich an den Modulen arbeiten und dort die Performance Probleme lösen.

Duration | View
-- | --
1403.0 | gems/decidim-meetings-0.23.1/app/views/decidim/meetings/directory/meetings/index.html.erb within layouts/decidim/application
1129.3 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_application.html.erb
1100.5 | gems/decidim-meetings-0.23.1/app/views/decidim/meetings/directory/meetings/_meetings.html.erb
979.4 | gems/decidim-decidim_awesome-0.6.2/app/views/layouts/decidim/_head.html.erb
977.6 | gems/decidim-decidim_awesome-0.6.2/app/views/v0.23/layouts/decidim/_head.html.erb
87.1 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_wrapper.html.erb
23.5 | layouts/decidim/_main_footer.html.erb
12.5 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_mini_footer.html.erb
8.5 | gems/decidim-core-0.23.1/app/views/decidim/shared/_login_modal.html.erb
8.1 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_topbar_search.html.erb
4.5 | gems/decidim-decidim_awesome-0.6.2/app/views/layouts/decidim/decidim_awesome/_awesome_config.html.erb
4.2 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_js_configuration.html.erb
4.0 | gems/decidim-meetings-0.23.1/app/views/decidim/meetings/_calendar_modal.html.erb
1.8 | gems/decidim-core-0.23.1/app/views/decidim/shared/_results_per_page.html.erb
1.4 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_social_media_links.html.erb
1.3 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_impersonation_warning.html.erb
1.3 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_logo.html.erb
0.9 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_omnipresent_banner.html.erb
0.8 | layouts/decidim/_head_extra.html.erb
0.6 | gems/decidim-core-0.23.1/app/views/decidim/shared/_confirm_modal.html.erb
0.5 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_language_chooser.html.erb
0.5 | gems/decidim-core-0.23.1/app/views/decidim/devise/shared/_omniauth_buttons_mini.html.erb
0.4 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_cookie_warning.html.erb
0.4 | gems/decidim-core-0.23.1/app/views/decidim/shared/_authorization_modal.html.erb
0.3 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_organization_colors.html.erb
0.3 | gems/decidim-core-0.23.1/app/views/layouts/decidim/_admin_links.html.erb

**Comment by innosmith** [comment]
Als Plattform-Admin sehe ich keine Einstellungsmöglichkeiten, das Veranstaltungsmodul zu optimieren in Bezug auf Performance. Haben andere Decidim-User noch nie Perfomance-Issues mit Veranstaltungen oder anderen Core-Komponenten gemeldet?

**Comment by Kagemaru** [comment]
Doch, für v0.24.0 haben Sie genau dies gemacht und bei den Core-Modules die Performance verbessert.
Auszug aus https://github.com/decidim/decidim/releases:
>**decidim-accountability, decidim-core, decidim-meetings, decidim-proposals:** Optimize queries for performance in Homepage, process page, proposals page and coauthorable cell. #5903

**Comment by innosmith** [comment]
Das tönt vielversprechend. Dann warten wir mit weiteren Performance-Optimierungen auf v0.24.

**Comment by innosmith** [comment]
Performance mit dem Update ist bedeutend besser geworden. Am Langsamsten sind immer noch die Veranstaltungen.
