### ISSUE TITLE
Modul für Emailadress-Import

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#87]
Wir haben Listen von Emailadressen, welche wir gerne zu Dialog Luzern einladen möchten. Unter anderem registrierter User der bisherigen Quartierplattform. Hierfür gibt es ein Decidim-Modul, welches solche Aufgaben erlaubt. Bitte auf INT installieren.

https://github.com/Platoniq/decidim-verifications-direct_verifications

**Comment by Kagemaru** [comment]
Dieses Modul gibt es noch nicht für 0.23
Falls gewünscht kann ich die Zeit aufwenden es zu forken und zu probieren es auf 0.23 zum Laufen zu bringen.

**Comment by Kagemaru** [comment]
Auf der Github Page gibt es [Tags für die verfügbaren Versionen](https://github.com/Platoniq/decidim-verifications-direct_verifications/tags). Die letzte Version da ist v0.22.1.

**Comment by innosmith** [comment]
Dann warten wir noch etwas zu, bis wir die Funktion zwingend benötigen für die Migration der alten Quartier-Plattform nach Dialog Luzern. Allenfalls macht es dann mehr Sinn, gleich mit v0.24 kompatibel zu machen.

**Comment by innosmith** [comment]
Bitte den Aufwand schätzen. Wir wissen noch nicht genau, ob wir diese Funktion dann wirklich benötigen.

**Comment by carlobeltrame** [comment]
Grobschätzung: 0.5 - 1PT wenn das Modul sich problemlos auf decidim 0.24+ updaten lässt. Unbekannte Aufwände könnten aber auftauchen, wenn sich dabei Komplikationen ergeben.

**Comment by innosmith** [comment]
Warten auf Abstimmung mit QUIN bez. Ablösung VQSL-Website und allfälliger Datenimport. Dito allenfalls für die Ablösung der Vereinsliste.

**Comment by innosmith** [comment]
In Abstimmung mit QUIN am 25.06.2021 wird dieses Modul nicht benötigt.
