### ISSUE TITLE
Änderungen von Vorschlägen auf unbestimmte Zeit zulassen

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#92]
Mit der Eingabe von einer sehr langen Zahl kann dies heute schon gemacht werden. Könnt ihr sehen, wo die Grenze ist?

**Comment by carlobeltrame** [comment]
Es gibt keine explizite Grenze. Ich empfehle, eine Zahl wie 99999999999 zu verwenden (entspricht fast 200'000 Jahren...)
Mit decidim 0.24 kommt die Möglichkeit, [die Beschränkung ganz aufzuheben](https://github.com/decidim/decidim/pull/7406).
