### ISSUE TITLE
Bilder hochladen nicht möglich auf Testplattform

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#98]
Einer unserer Vereine konnte keine Bilder im Editor hochladen. Wir haben es im Firefox und Edge versucht. Sowohl mit seinen Bildern und einem Bild, dass ich ihm gesendet habe, mit dem es bei mir funktioniert hat.

Bei mir geht es problemlos.

 Er nutzt als Standard ein Foto-Editor Tool und die Fotos haben dann unter Format die Bezeichnung acdseeJPEG. Könnte das die Ursache sein?

**Comment by carlobeltrame** [comment]
Also verstehe ich das richtig, es klappt auch nicht wenn er ein Bild hochlädt das du problemlos hochladen kannst?

**Comment by Naadjjaa** [comment]
Ja, genau. Ich habe es mit dem Bild versucht, es ihm gesendet, er hat es auf dem Desktop gespeichert (angezeigt wurde es dann auch als acdseejpeg Format) und er konnte den Editor öffnen, das Bild auswählen aber es konnte nicht hochgeladen werden. (Windows 10)

**Comment by carlobeltrame** [comment]
Also wenn er das Bild nicht bearbeitet hat scheint mir das sehr seltsam. Hat er vielleicht ein Browser-Plugin das das noch beeinflussen könte?

Ich glaube wir machen am besten mal einen Video-Call wo er uns live zeigt wie er das Bild hochlädt und ich gleich in den Logs nachsehen kann was da schief geht.

**Comment by Naadjjaa** [comment]
Ich hatte gerade nochmals eine Anwenderin, welche dasselbe Problem hat. Kannst du mir per Mail einige Slots senden, an denen du Zeit hättest?

**Comment by Naadjjaa** [comment]
Bin gerade als Organisations-Admin eingeloggt und mit diesen Rechten geht es bei mir auch nicht die Bilder hochzuladen.

**Comment by carlobeltrame** [comment]
Aha, guter Hinweis, dann forsche ich da mal nach. Mit "hochladen" meinst du die Bilder in den Text-Editor ziehen, oder?

**Comment by Naadjjaa** [comment]
Korrekt oder via "Bild Icon" hochladen.

**Comment by Kagemaru** [comment]
Testen mit Browserstack, wahrscheinlich wegen Organisationsadmin

**Comment by carlobeltrame** [comment]
Ich konnte das inzwischen reproduzieren, und es ist auch bereits seit kurzem bei Decidim Awesome gemeldet: https://github.com/Platoniq/decidim-module-decidim_awesome/issues/112

Es scheint auf die eine oder andere Art ein Permissions-Problem zu sein. Leider sehe ich da zu wenig weit dahinter, um den Fehler gleich in kurzer Zeit zu erkennen und zu fixen. Ich müsste wohl ca. 1-2 Tage da reinstecken, wenn wir das selber fixen wollen.

**Comment by Naadjjaa** [comment]
Da es auf PROD gemäss meinem Test funktioniert, schliesse ich dieses Ticket.
