### ISSUE TITLE
Iframe von allen Komponenten möglich?

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-ocl#99]
Bitte prüfen, noch nicht umsetzen:

Die Informations-Seite von Assemblies und Processes lässt sich via simplem Klick auf Drittseiten einbetten. Wieso gibt es diese Funktion für andere Komponenten nicht? Wie kompliziert schätzt ihr die Umsetzung dieses Features? 

Gerade bei Veranstaltungen ist es für unsere Pilotanwender/innen bereits oft zur Sprache gekommen.

**Comment by Naadjjaa** [comment]
![Einbetten](https://user-images.githubusercontent.com/75797851/114031756-f7292400-987b-11eb-9d82-ca1ef0b8c88d.PNG)

**Comment by carlobeltrame** [comment]
Machbar wäre das wohl schon. Hast du dir denn eine eingebettete Organisation schon mal angeschaut? Eingebettet wird dann nicht die "Informations-Seite", sondern nur eine kleine Übersichts-Kachel. Das sieht dann ungefähr so aus:
![Screenshot from 2021-04-08 16-25-14](https://user-images.githubusercontent.com/7566995/114044017-1c6f5f80-9887-11eb-8b64-f4897c7fa3e6.png)

Für jede Komponente müsste man dann also zuerst definieren, wie sie genau aussehen soll wenn sie eingebettet ist. Es gibt auf jeden Fall nicht eine "one fits all" Lösung für alle denkbaren Arten von Komponenten.

Ich vermute bisher hat sich dafür einfach noch niemand in der decidim-Community genügend stark interessiert, bzw. ist es für User oft einfacher einfach einen Link zu teilen, und das Einbetten ist daher bisher nicht implementiert worden.
